Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2018-10, with the labels that each got.

#1224 Improve error messages for recursive instance delete
  app/actions/service_binding_delete.rb
  app/actions/services/locks/lock_check.rb
  app/actions/services/service_key_delete.rb
  lib/services/service_brokers/v2/client.rb
  spec/acceptance/async_bindings_spec.rb
  spec/unit/actions/service_binding_delete_spec.rb
  spec/unit/actions/services/service_instance_delete_spec.rb
  spec/unit/actions/services/service_key_delete_spec.rb
  spec/unit/controllers/services/service_bindings_controller_spec.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/controllers/services/service_keys_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  vendor/errors/v2.yml
Labels: sapi, unscheduled

#1229 Fix service broker plan updates requiring strict ordering
  lib/services/service_brokers/service_manager.rb
  spec/acceptance/service_broker_spec.rb
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
Labels: sapi, unscheduled

#1228 Add the service broker name to responses on services resource
  app/presenters/v2/presenter_provider.rb
  app/presenters/v2/service_presenter.rb
  docs/v2/organizations/list_all_services_for_the_organization.html
  docs/v2/services/list_all_services.html
  docs/v2/services/retrieve_a_particular_service.html
  docs/v2/spaces/list_all_services_for_the_space.html
  spec/request/v2/organizations_spec.rb
  spec/request/v2/services_spec.rb
  spec/request/v2/spaces_spec.rb
  spec/unit/controllers/services/services_controller_spec.rb
  spec/unit/presenters/v2/service_presenter_spec.rb
Labels: sapi, unscheduled

#1234 Bundle install before running check_docs_links
  Rakefile
Labels: unscheduled

#1232 Fixing typo in current result for issue template
  ISSUE_TEMPLATE.md
Labels: unscheduled

#1227 Check for nil entries in bulk sync call
  lib/cloud_controller/copilot/adapter.rb
  lib/cloud_controller/copilot/sync.rb
  spec/unit/lib/cloud_controller/copilot/adapter_spec.rb
  spec/unit/lib/cloud_controller/copilot/sync_spec.rb
Labels: unscheduled

#1222 Allows service brokers to be registered more than once with different names
  app/models/services/service.rb
  app/models/services/service_broker.rb
  app/models/services/service_plan.rb
  db/migrations/20180921102908_remove_uniqueness_on_index_broker_url_from_service_brokers.rb
  db/migrations/20180924142348_remove_uniqueness_on_index_unique_id_from_services.rb
  db/migrations/20180924142407_remove_uniqueness_on_index_unique_id_from_service_plans.rb
  db/migrations/20180925150440_remove_services_label_provider_index.rb
  lib/services/service_brokers/v2/catalog.rb
  lib/services/service_brokers/v2/catalog_plan.rb
  spec/acceptance/service_broker_spec.rb
  spec/unit/controllers/services/service_brokers_controller_spec.rb
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
  spec/unit/lib/services/service_brokers/v2/catalog_plan_spec.rb
  spec/unit/lib/services/service_brokers/v2/catalog_spec.rb
  spec/unit/models/services/service_broker_spec.rb
  spec/unit/models/services/service_plan_spec.rb
  spec/unit/models/services/service_spec.rb
Labels: sapi, unscheduled

#1223 Add service broker name + guid to ServiceUsageEvent
  app/models/services/service_usage_event.rb
  app/repositories/service_usage_event_repository.rb
  db/migrations/20180927105539_add_broker_name_and_guid_to_service_usage_event.rb
  docs/v2/service_usage_events/list_service_usage_events.html
  docs/v2/service_usage_events/retrieve_a_particular_service_usage_event.html
  spec/support/matchers/match_service_instance.rb
  spec/unit/models/services/service_usage_event_spec.rb
  spec/unit/repositories/service_usage_event_repository_spec.rb
Labels: sapi, unscheduled

#1238 Add tests for multiple plans and services with identical ids
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
Labels: sapi, unscheduled

#1239 Document 'hide marketplace' and 'service instance sharing' feature flags
  docs/v2/feature_flags/get_all_feature_flags.html
  docs/v2/feature_flags/get_the_hide_marketplace_from_unauthenticated_users.html
  docs/v2/feature_flags/get_the_service_instance_sharing_feature_flag.html
  docs/v2/index.html
Labels: sapi, unscheduled

#1236 add batching to Copilot::Sync
  lib/cloud_controller/copilot/sync.rb
  spec/unit/lib/cloud_controller/copilot/sync_spec.rb
Labels: unscheduled

#1205 Enable pluggable container orchestration using OPI
  config/cloud_controller.yml
  lib/cloud_controller/config_schemas/api_schema.rb
  lib/cloud_controller/config_schemas/clock_schema.rb
  lib/cloud_controller/config_schemas/deployment_updater_schema.rb
  lib/cloud_controller/config_schemas/worker_schema.rb
  lib/cloud_controller/dependency_locator.rb
  lib/cloud_controller/diego/bbs_apps_client.rb
  lib/cloud_controller/diego/desire_app_handler.rb
  lib/cloud_controller/diego/messenger.rb
  lib/cloud_controller/diego/processes_sync.rb
  lib/cloud_controller/diego/runner.rb
  lib/cloud_controller/opi/apps_client.rb
  lib/cloud_controller/opi/instances_client.rb
  spec/integration/opi_apps_client_spec.rb
  spec/integration/opi_instances_client_spec.rb
  spec/spec_helper.rb
  spec/unit/controllers/services/lifecycle/service_instance_binding_manager_spec.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
  spec/unit/lib/cloud_controller/diego/bbs_apps_client_spec.rb
  spec/unit/lib/cloud_controller/diego/desire_app_handler_spec.rb
  spec/unit/lib/cloud_controller/diego/messenger_spec.rb
  spec/unit/lib/cloud_controller/diego/processes_sync_spec.rb
  spec/unit/lib/cloud_controller/diego/runner_spec.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
  spec/unit/lib/cloud_controller/opi/instances_client_spec.rb
Labels: PM Review, in progress

#1244 Pass internal route flag to copilot
  Gemfile
  Gemfile.lock
  lib/cloud_controller/copilot/adapter.rb
  spec/unit/lib/cloud_controller/copilot/adapter_spec.rb
Labels: unscheduled
