Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2018-07, with the labels that each got.

#1171 Mark route binding parameters as experimental
  docs/v2/index.html
  docs/v2/service_instances/retrieve_a_particular_route_binding_parameters.html
Labels: unscheduled

#1174 Continue polling on 410 from last_operation endpoint
  lib/services/service_brokers/v2/client.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: unscheduled

#1172 Refactor some compound conditionals on services
  app/actions/services/service_binding_read.rb
  app/controllers/services/service_bindings_controller.rb
  app/models/services/service_plan_visibility.rb
Labels: sapi, unscheduled

#1175 Pass credentials to bits-service-client ResourcePool, bump major version
  Gemfile
  Gemfile.lock
  lib/cloud_controller/dependency_locator.rb
Labels: in progress

#1183 Broker dashboard_url's can be null
  lib/services/service_brokers/v2/response_parser.rb
  spec/unit/actions/services/service_instance_update_spec.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: sapi, unscheduled
