Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-10, with the labels that each got.

#1458 Revert "Revert "Add docker support in Eirini""
  lib/cloud_controller/opi/apps_client.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
Labels: unscheduled

#1461 Rename 'credentials' to 'authentication' when creating a service broker
  app/actions/service_broker_create.rb
  app/messages/service_broker_create_message.rb
  docs/v3/source/includes/api_resources/_service_brokers.erb
  docs/v3/source/includes/experimental_resources/service_brokers/_create.md.erb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/messages/service_broker_create_message_spec.rb
Labels: sapi, unscheduled

#1464 V3 async delete broker 168511247
  README.md
  app/actions/service_binding_create.rb
  app/actions/service_broker_create.rb
  app/actions/services/service_instance_create.rb
  app/controllers/v3/service_brokers_controller.rb
  app/jobs/delete_action_job.rb
  app/jobs/pollable_job_wrapper.rb
  app/jobs/v2/services/asynchronous_operations.rb
  app/jobs/v2/services/delete_orphaned_binding.rb
  app/jobs/v2/services/delete_orphaned_instance.rb
  app/jobs/v2/services/delete_orphaned_key.rb
  app/jobs/v2/services/legacy_jobs/service_instance_deletion.rb
  app/jobs/v2/services/service_binding_state_fetch.rb
  app/jobs/v2/services/service_instance_state_fetch.rb
  app/jobs/v2/services/service_usage_events_cleanup.rb
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  app/jobs/wrapping_job.rb
  app/models.rb
  app/models/runtime/job_warning_model.rb
  app/models/runtime/pollable_job_model.rb
  app/models/services/service_broker.rb
  app/models/services/service_broker_state_enum.rb
  app/presenters/v3/job_presenter.rb
  app/presenters/v3/service_broker_presenter.rb
  db/migrations/20190923131251_create_job_warnings_table.rb
  lib/cloud_controller/jobs.rb
  lib/services/service_brokers/service_broker_remover.rb
  lib/services/service_brokers/v2/orphan_mitigator.rb
  spec/request/jobs_spec.rb
  spec/request/service_brokers_spec.rb
  spec/request_spec_shared_examples.rb
  spec/support/fakes/blueprints.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/support/shared_examples/jobs/delayed_job.rb
  spec/unit/controllers/v3/service_brokers_controller_spec.rb
  spec/unit/jobs/pollable_job_wrapper_spec.rb
  spec/unit/jobs/services/service_binding_state_fetch_spec.rb
  spec/unit/jobs/services/service_instance_state_fetch_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
  spec/unit/jobs/wrapping_job_spec.rb
  spec/unit/lib/services/service_brokers/service_broker_remover_spec.rb
  spec/unit/models/runtime/pollable_job_model_spec.rb
  spec/unit/presenters/v3/job_presenter_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: sapi, unscheduled

#1462 Create service broker can fail/produce warnings
  README.md
  app/actions/service_binding_create.rb
  app/actions/service_broker_create.rb
  app/actions/services/service_instance_create.rb
  app/jobs/pollable_job_wrapper.rb
  app/jobs/v2/services/asynchronous_operations.rb
  app/jobs/v2/services/delete_orphaned_binding.rb
  app/jobs/v2/services/delete_orphaned_instance.rb
  app/jobs/v2/services/delete_orphaned_key.rb
  app/jobs/v2/services/legacy_jobs/service_instance_deletion.rb
  app/jobs/v2/services/service_binding_state_fetch.rb
  app/jobs/v2/services/service_instance_state_fetch.rb
  app/jobs/v2/services/service_usage_events_cleanup.rb
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  app/jobs/wrapping_job.rb
  app/models.rb
  app/models/runtime/job_warning_model.rb
  app/models/runtime/pollable_job_model.rb
  app/presenters/v3/job_presenter.rb
  db/migrations/20190923131251_create_job_warnings_table.rb
  lib/cloud_controller/jobs.rb
  lib/services/service_brokers/v2/orphan_mitigator.rb
  spec/request/jobs_spec.rb
  spec/request/service_brokers_spec.rb
  spec/request_spec_shared_examples.rb
  spec/support/fakes/blueprints.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/support/shared_examples/jobs/delayed_job.rb
  spec/unit/jobs/pollable_job_wrapper_spec.rb
  spec/unit/jobs/services/service_binding_state_fetch_spec.rb
  spec/unit/jobs/services/service_instance_state_fetch_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
  spec/unit/jobs/wrapping_job_spec.rb
  spec/unit/models/runtime/pollable_job_model_spec.rb
  spec/unit/presenters/v3/job_presenter_spec.rb
Labels: sapi, unscheduled

#1467 Create broker audit events for V3 should reflect V3 request structure
  app/actions/service_broker_create.rb
  app/messages/service_broker_create_message.rb
  app/repositories/service_event_repository.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/messages/service_broker_create_message_spec.rb
  spec/unit/repositories/service_event_repository_spec.rb
Labels: sapi, unscheduled

#1473 PATCH requests to /v3/service_brokers/:service_broker_guid failure scenarios
  app/actions/v3/service_broker_update.rb
  app/models/services/service_broker.rb
  docs/v3/source/includes/experimental_resources/service_brokers/_update.md.erb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
  spec/unit/models/services/service_broker_spec.rb
Labels: unscheduled

#1459 only create start usage events for RUNNING tasks
  app/models/runtime/task_model.rb
  spec/unit/models/runtime/task_model_spec.rb
Labels: scheduled

#1468 Enable docker support for OPI staging
  lib/cloud_controller/opi/stager_client.rb
  spec/unit/lib/cloud_controller/opi/stager_client_spec.rb
Labels: in progress, k8s

#1480 Fix error when deactivated plan warning is issued.
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  spec/request/service_brokers_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
Labels: sapi, unscheduled

#1481 Improve validation failure when service broker URL is not valid.
  app/messages/validators/url_validator.rb
  spec/unit/messages/validators/url_validator_spec.rb
Labels: sapi, unscheduled
