Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-05, with the labels that each got.

#1338 Add V3 list service brokers endpoint
  app/controllers/v3/root_controller.rb
  app/controllers/v3/service_brokers_controller.rb
  app/fetchers/service_broker_list_fetcher.rb
  app/messages/service_brokers_list_message.rb
  app/presenters/v3/service_broker_presenter.rb
  config/routes.rb
  docs/v3/source/includes/api_resources/_service_brokers.erb
  docs/v3/source/includes/experimental_resources/service_brokers/_header.md
  docs/v3/source/includes/experimental_resources/service_brokers/_list.md.erb
  docs/v3/source/includes/experimental_resources/service_brokers/_object.md.erb
  docs/v3/source/index.md
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/service_brokers_spec.rb
  spec/request/v3_root_spec.rb
  spec/unit/controllers/v3/root_controller_spec.rb
  spec/unit/fetchers/service_broker_list_fetcher_spec.rb
  spec/unit/messages/service_brokers_list_message_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: sapi, unscheduled

#1345 Add endpoint GET /v3/service_brokers/:guid
  app/access/service_access.rb
  app/access/service_broker_access.rb
  app/access/service_instance_access.rb
  app/controllers/services/service_instances_controller.rb
  app/controllers/v3/service_brokers_controller.rb
  app/fetchers/service_broker_list_fetcher.rb
  app/models/services/service_broker.rb
  app/models/services/service_plan.rb
  app/models/services/service_plan_visibility.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_brokers/_get.md.erb
  docs/v3/source/index.md
  lib/cloud_controller/perm/permissions.rb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/service_brokers_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
  spec/unit/lib/perm/permissions_spec.rb
  spec/unit/lib/permissions/queryer_spec.rb
  spec/unit/models/services/service_broker_spec.rb
  spec/unit/models/services/service_plan_spec.rb
Labels: sapi, unscheduled

#1326 Suggest logging in when unauthenticated users get rate-limited
  middleware/rate_limiter.rb
  spec/unit/middleware/rate_limiter_spec.rb
  vendor/errors/v2.yml
Labels: scheduled

#1346 Mark the service_brokers link as experimental in v3
  app/controllers/v3/root_controller.rb
  spec/request/v3_root_spec.rb
Labels: sapi, unscheduled

#1348 V3 service brokers contain a link to the associated space
  app/presenters/v3/service_broker_presenter.rb
  docs/v3/source/includes/api_resources/_service_brokers.erb
  spec/request/service_brokers_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: unscheduled

#1341 Delete critical file
  newfile
Labels: unscheduled

#1347 fix passing application env vars to eirini
  lib/cloud_controller/opi/env_hash.rb
  lib/cloud_controller/opi/stager_client.rb
  spec/unit/lib/cloud_controller/opi/stager_client_spec.rb
Labels: unscheduled

#1340 Add internal api docs
  docs/internal/README.md
Labels: unscheduled

#1351 Add POST /v3/service_brokers to create new service broker
  app/actions/v3/service_broker_create.rb
  app/controllers/v3/service_brokers_controller.rb
  app/repositories/service_event_repository.rb
  config/routes.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/service_brokers_spec.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/unit/actions/v3/service_broker_create_spec.rb
  spec/unit/repositories/service_event_repository_spec.rb
Labels: sapi, unscheduled

#1350 Add favicon to v3 API docs
  docs/v3/source/images/favicon.ico
  docs/v3/source/layouts/layout.erb
Labels: unscheduled

#1352 Async service bindings feature is no longer experimental
  docs/v2/service_bindings/create_a_service_binding.html
  docs/v2/service_bindings/delete_a_particular_service_binding.html
Labels: sapi, unscheduled

#1349 Add maintenance_info to the service_instance and enable update
  app/actions/services/service_instance_create.rb
  app/actions/services/service_instance_update.rb
  app/controllers/services/validators/service_update_validator.rb
  app/models/services/managed_service_instance.rb
  app/models/services/service_plan.rb
  app/presenters/mixins/services_presentation_helpers.rb
  app/presenters/v2/service_instance_presenter.rb
  app/presenters/v2/service_plan_presenter.rb
  db/migrations/20190503090026_add_maintenance_info_to_service_instance.rb
  docs/v2/service_instances/creating_a_service_instance.html
  docs/v2/service_instances/delete_a_service_instance.html
  docs/v2/service_instances/list_all_service_instances.html
  docs/v2/service_instances/retrieve_a_particular_service_instance.html
  docs/v2/service_instances/update_a_service_instance.html
  docs/v2/service_plans/list_all_service_instances_for_the_service_plan.html
  docs/v2/spaces/list_all_service_instances_for_the_space.html
  lib/services/service_brokers/service_manager.rb
  lib/services/service_brokers/v2/client.rb
  spec/request/v2/service_bindings_spec.rb
  spec/request/v2/service_instances_spec.rb
  spec/request/v2/service_plans_spec.rb
  spec/request/v2/spaces_spec.rb
  spec/support/service_broker_helpers.rb
  spec/unit/actions/services/service_instance_create_spec.rb
  spec/unit/actions/services/service_instance_update_spec.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/controllers/services/validators/service_update_validator_spec.rb
  spec/unit/jobs/services/service_instance_state_fetch_spec.rb
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  spec/unit/models/services/managed_service_instance_spec.rb
  spec/unit/presenters/v2/service_instance_presenter_spec.rb
  spec/unit/presenters/v2/service_plan_presenter_spec.rb
Labels: review-requested, sapi, scheduled
