Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-09, with the labels that each got.

#1416 Bind failure during push shows service name
  app/actions/app_apply_manifest.rb
  app/jobs/app_apply_manifest_action_job.rb
  app/jobs/space_apply_manifest_action_job.rb
  spec/request/app_manifests_spec.rb
  spec/request/space_manifests_spec.rb
  spec/unit/actions/app_apply_manifest_spec.rb
  spec/unit/jobs/app_apply_manifest_action_job_spec.rb
  spec/unit/jobs/space_apply_manifest_action_job_spec.rb
Labels: sapi, unscheduled

#1410 ports field no longer experimental
  docs/v2/apps/updating_an_app.html
Labels: unscheduled

#1427 V3 service broker delete 166631760
  Gemfile
  Gemfile.lock
  app/controllers/v3/service_brokers_controller.rb
  bin/rspec
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_brokers/_delete.md.erb
  docs/v3/source/index.md
  spec/request/service_brokers_spec.rb
  spec/support/controller_helpers.rb
  spec/support/matchers/be_reported_as_events.rb
  spec/support/matchers/find_broker.rb
  spec/support/matchers/match_broker.rb
  spec/support/service_broker_helpers.rb
  spec/support/shared_examples/request/service_brokers.rb
  spec/support/user_helpers.rb
  spec/unit/controllers/v3/service_bindings_controller_spec.rb
  spec/unit/controllers/v3/service_brokers_controller_spec.rb
Labels: sapi, unscheduled

#1435 Add log-cache endpoint to /
  app/controllers/runtime/root_controller.rb
  config/cloud_controller.yml
  lib/cloud_controller/config_schemas/api_schema.rb
  spec/unit/controllers/runtime/root_controller_spec.rb
Labels: unscheduled

#1440 As a v3 API user, my POST requests to /v3/service_brokers are asynchronous
  app/actions/service_broker_create.rb
  app/actions/v2/services/service_broker_create.rb
  app/controllers/services/service_brokers_controller.rb
  app/controllers/v3/service_brokers_controller.rb
  app/jobs/v3/synchronize_broker_catalog_job.rb
  app/models.rb
  app/models/services/service_broker.rb
  app/models/services/service_broker_state.rb
  app/models/services/service_broker_state_enum.rb
  app/presenters/v3/base_presenter.rb
  app/presenters/v3/service_broker_presenter.rb
  app/repositories/service_event_repository.rb
  db/migrations/20190905131313_create_service_broker_states.rb
  lib/cloud_controller/diego/buildpack/staging_action_builder.rb
  lib/services/service_brokers/v2/catalog.rb
  spec/lightweight_spec_helper.rb
  spec/request/service_brokers_spec.rb
  spec/support/bootstrap/test_config.rb
  spec/support/fakes/blueprints.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/support/link_helpers.rb
  spec/support/matchers/match_broker.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/controllers/v3/service_brokers_controller_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
  spec/unit/lib/services/service_brokers/v2/catalog_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
  vendor/errors/v2.yml
Labels: sapi, unscheduled

#1430 When pruning app and service usage events, ensure at least one record is kept
  app/repositories/app_usage_event_repository.rb
  app/repositories/service_usage_event_repository.rb
  lib/database/old_record_cleanup.rb
  spec/unit/jobs/runtime/app_usage_events_cleanup_spec.rb
  spec/unit/jobs/services/service_usage_events_cleanup_spec.rb
  spec/unit/lib/database/old_record_cleanup_spec.rb
  spec/unit/repositories/app_usage_event_repository_spec.rb
  spec/unit/repositories/service_usage_event_repository_spec.rb
Labels: in progress

#1417 Add docker support in Eirini
  lib/cloud_controller/opi/apps_client.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
Labels: unscheduled

#1407 Access service usage events as global auditor
  app/access/service_usage_event_access.rb
  spec/unit/access/service_usage_event_access_spec.rb
Labels: unscheduled

#1421 Default new_memory to 0 in sidecar validator
  app/models/runtime/constraints/sidecar_memory_less_than_process_memory_policy.rb
  spec/unit/models/runtime/constraints/sidecar_memory_less_than_process_memory_policy_spec.rb
Labels: unscheduled

#1423 Upgrade fog-aliyun to 0.3.5
  Gemfile.lock
Labels: unscheduled

#1439 Add embedded app relationship to app sub-resources
  app/presenters/v3/build_presenter.rb
  app/presenters/v3/droplet_presenter.rb
  app/presenters/v3/package_presenter.rb
  app/presenters/v3/process_presenter.rb
  app/presenters/v3/task_presenter.rb
  docs/v3/source/includes/api_resources/_builds.erb
  docs/v3/source/includes/api_resources/_droplets.erb
  docs/v3/source/includes/api_resources/_packages.erb
  docs/v3/source/includes/api_resources/_processes.erb
  docs/v3/source/includes/api_resources/_tasks.erb
  docs/v3/source/includes/resources/builds/_object.md.erb
  docs/v3/source/includes/resources/droplets/_object.md.erb
  docs/v3/source/includes/resources/packages/_object.md.erb
  docs/v3/source/includes/resources/processes/_object.md.erb
  docs/v3/source/includes/resources/tasks/_object.md.erb
  spec/request/apps_spec.rb
  spec/request/builds_spec.rb
  spec/request/droplets_spec.rb
  spec/request/packages_spec.rb
  spec/request/processes_spec.rb
  spec/request/tasks_spec.rb
  spec/unit/presenters/v3/build_presenter_spec.rb
  spec/unit/presenters/v3/droplet_presenter_spec.rb
  spec/unit/presenters/v3/package_presenter_spec.rb
  spec/unit/presenters/v3/process_presenter_spec.rb
  spec/unit/presenters/v3/task_presenter_spec.rb
Labels: unscheduled

#1431 Change include paths to match relationship names
  app/controllers/v3/apps_controller.rb
  app/controllers/v3/spaces_controller.rb
  app/decorators/include_app_organization_decorator.rb
  app/decorators/include_app_space_decorator.rb
  app/decorators/include_space_organization_decorator.rb
  app/messages/app_show_message.rb
  app/messages/apps_list_message.rb
  app/messages/space_show_message.rb
  app/messages/spaces_list_message.rb
  docs/v3/source/includes/concepts/_includes.md.erb
  docs/v3/source/includes/resources/apps/_get.md.erb
  docs/v3/source/includes/resources/apps/_list.md.erb
  docs/v3/source/includes/resources/spaces/_get_a_space.md.erb
  docs/v3/source/includes/resources/spaces/_list.md.erb
  spec/request/apps_spec.rb
  spec/request/spaces_spec.rb
  spec/unit/decorators/include_app_organization_decorator_spec.rb
  spec/unit/decorators/include_app_space_decorator_spec.rb
  spec/unit/decorators/include_space_organization_decorator_spec.rb
  spec/unit/messages/app_show_message_spec.rb
  spec/unit/messages/apps_list_message_spec.rb
  spec/unit/messages/space_show_message_spec.rb
  spec/unit/messages/spaces_list_message_spec.rb
Labels: unscheduled

#1450 Revert "Add docker support in Eirini"
  lib/cloud_controller/opi/apps_client.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
Labels: unscheduled
