Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-06, with the labels that each got.

#1353 Remove experimental flag from retrieving parameters endpoints
  docs/v2/index.html
  docs/v2/service_bindings/retrieve_a_particular_service_binding_parameters.html
  docs/v2/service_instances/retrieve_a_particular_route_binding_parameters.html
  docs/v2/service_instances/retrieve_a_particular_service_instance_parameters.html
Labels: sapi, unscheduled

#1359 Handle warnings while creating service broker
  app/actions/service_broker_create.rb
  app/controllers/v3/application_controller.rb
  app/controllers/v3/service_brokers_controller.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/actions/v3/service_broker_create_spec.rb
  spec/unit/controllers/v3/application_controller_spec.rb
Labels: review-requested, sapi

#1360 Make POST /v3/service_brokers extensible to support different authentication types
  app/actions/service_broker_create.rb
  app/controllers/v3/service_brokers_controller.rb
  app/messages/service_broker_create_message.rb
  docs/v3/source/includes/experimental_resources/service_brokers/_create.md.erb
  docs/v3/source/index.md
  spec/lightweight_spec_helper.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/messages/service_broker_create_message_spec.rb
Labels: sapi

#1366 Reject maintenance_info with extra keys
  lib/services/service_brokers/v2/catalog_plan.rb
  spec/unit/lib/services/service_brokers/v2/catalog_plan_spec.rb
Labels: sapi, unscheduled

#1368 Validation for metadata.shareable on the service broker catalog
  lib/services/service_brokers/v2/catalog_service.rb
  spec/unit/lib/services/service_brokers/v2/catalog_service_spec.rb
Labels: sapi, unscheduled

#1371 Add maintenance_info description to instances and plans
  docs/v2/apps/get_app_summary.html
  docs/v2/service_instances/retrieve_a_particular_service_instance.html
  docs/v2/service_instances/update_a_service_instance.html
  docs/v2/service_plans/retrieve_a_particular_service_plan.html
  docs/v2/spaces/get_space_summary.html
  lib/services/service_brokers/v2/catalog_plan.rb
  spec/acceptance/broker_api_compatibility/broker_api_v2.15_spec.rb
  spec/request/v2/service_instances_spec.rb
  spec/request/v2/service_plans_spec.rb
  spec/request/v2/spaces_spec.rb
  spec/unit/lib/services/service_brokers/v2/catalog_plan_spec.rb
Labels: unscheduled

#1370 [Documentation] Fix Broken Links
  CONTRIBUTING.md
Labels: unscheduled

#1361 Cloud Controller now sends its VIPs to copilot
  Gemfile
  Gemfile.lock
  lib/cloud_controller/config_schemas/route_syncer_schema.rb
  lib/cloud_controller/copilot/adapter.rb
  lib/cloud_controller/copilot/sync.rb
  spec/unit/lib/cloud_controller/copilot/adapter_spec.rb
  spec/unit/lib/cloud_controller/copilot/sync_spec.rb
Labels: unscheduled

#1369 Upgrade v3 docs favicon to be web 3.0 compatible
  docs/v3/source/images/favicon.ico
Labels: unscheduled
