Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-11, with the labels that each got.

#1486 Make /v3 API service broker patches atomic
  app/actions/service_broker_create.rb
  app/actions/v3/service_broker_update.rb
  app/jobs/v3/services/service_broker_catalog_updater.rb
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  app/jobs/v3/services/update_broker_job.rb
  app/models.rb
  app/models/services/service_broker_update_request.rb
  db/migrations/20191031135500_create_service_broker_update_requests.rb
  spec/request/lifecycle/service_brokers_spec.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
  spec/unit/jobs/v3/update_broker_job_spec.rb
Labels: sapi, unscheduled

#1487 As a /v3 API user, I want to GET a single service offering using a GUID
  app/controllers/v3/service_offerings_controller.rb
  app/presenters/v3/service_offering_presenter.rb
  spec/request/service_offerings_spec.rb
  spec/unit/presenters/v3/service_offering_presenter_spec.rb
Labels: delivered, sapi

#1457 Implement no-op Task client for OPI
  lib/cloud_controller/dependency_locator.rb
  lib/cloud_controller/opi/task_client.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
  spec/unit/lib/cloud_controller/opi/task_client_spec.rb
Labels: k8s, unscheduled

#1489 Show brokers created using /v2 API in `available` state
  app/presenters/v3/service_broker_presenter.rb
  spec/request/service_brokers_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: sapi, unscheduled

#1492 Refactor service offering request specs to use shared examples
  spec/request/service_brokers_spec.rb
  spec/request/service_offerings_spec.rb
Labels: sapi, unscheduled

#1493 Merge service broker states into service_brokers table
  app/actions/service_broker_create.rb
  app/actions/v3/service_broker_update.rb
  app/controllers/v3/service_brokers_controller.rb
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  app/jobs/v3/services/update_broker_job.rb
  app/models.rb
  app/models/services/service_broker.rb
  app/models/services/service_broker_state.rb
  app/presenters/v3/service_broker_presenter.rb
  db/migrations/20191112121711_add_state_to_service_brokers_table.rb
  db/migrations/20191112154745_drop_service_broker_states_table.rb
  lib/services/service_brokers/service_broker_remover.rb
  spec/request/service_brokers_spec.rb
  spec/support/fakes/blueprints.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
  spec/unit/jobs/v3/update_broker_job_spec.rb
  spec/unit/lib/services/service_brokers/service_broker_remover_spec.rb
  spec/unit/models/services/service_broker_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: sapi, unscheduled

#1491 Update random route generation to add 2 letter suffix
  lib/cloud_controller/random_route_generator.rb
  spec/unit/lib/cloud_controller/random_route_generator_spec.rb
Labels: unscheduled

#1482 Cut oversize error messages down so they'll fit in a 16K database field
  app/jobs/pollable_job_wrapper.rb
  app/presenters/v3/job_presenter.rb
  spec/request/service_brokers_spec.rb
  spec/unit/jobs/pollable_job_wrapper_spec.rb
  spec/unit/models/services/service_spec.rb
Labels: unscheduled

#1488 Remove workflows section of the docs
  docs/v3/source/includes/workflows/_workflows.md.erb
  docs/v3/source/index.md
Labels: unscheduled

#1490 Expand docs on lifecycle fields
  docs/v3/source/includes/resources/apps/_object.md.erb
  docs/v3/source/includes/resources/builds/_object.md.erb
  docs/v3/source/includes/resources/droplets/_object.md.erb
Labels: unscheduled

#1466 Refine metadata api doc alphanumeric wording
  docs/v3/source/includes/concepts/_metadata.md.erb
Labels: unscheduled

#1476 add ability to include domains on /v3/routes and /v3/routes/:guid
  app/controllers/v3/routes_controller.rb
  app/decorators/include_route_domain_decorator.rb
  app/messages/route_show_message.rb
  app/messages/routes_list_message.rb
  app/presenters/v3/route_presenter.rb
  docs/v3/source/includes/resources/routes/_get.md.erb
  docs/v3/source/includes/resources/routes/_list.md.erb
  spec/request/routes_spec.rb
  spec/unit/decorators/include_route_domain_decorator_spec.rb
  spec/unit/messages/route_show_message_spec.rb
  spec/unit/messages/routes_list_message_spec.rb
  spec/unit/presenters/v3/route_presenter_spec.rb
Labels: unscheduled

#1500 V3 service_offerings visibility for space-scoped offerings
  app/controllers/v3/service_offerings_controller.rb
  app/fetchers/service_offerings_fetcher.rb
  app/fetchers/service_plan_visibility_fetcher.rb
  spec/request/service_offerings_spec.rb
  spec/unit/fetchers/service_offerings_fetcher_spec.rb
  spec/unit/fetchers/service_plan_visibility_fetcher_spec.rb
Labels: sapi, unscheduled

#1501 V3 /v3/service_offerings/:guid - add links and relationships
  app/presenters/v3/service_offering_presenter.rb
  spec/request/service_offerings_spec.rb
  spec/unit/presenters/v3/service_offering_presenter_spec.rb
Labels: sapi, unscheduled

#1503 add ability to include domains on /v3/routes and /v3/routes/:guid
  app/controllers/v3/routes_controller.rb
  app/decorators/include_route_domain_decorator.rb
  app/messages/route_show_message.rb
  app/messages/routes_list_message.rb
  app/presenters/v3/route_presenter.rb
  docs/v3/source/includes/concepts/_includes.md.erb
  docs/v3/source/includes/resources/routes/_get.md.erb
  docs/v3/source/includes/resources/routes/_list.md.erb
  spec/request/routes_spec.rb
  spec/unit/decorators/include_route_domain_decorator_spec.rb
  spec/unit/messages/route_show_message_spec.rb
  spec/unit/messages/routes_list_message_spec.rb
  spec/unit/presenters/v3/route_presenter_spec.rb
Labels: unscheduled
