Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-04, with the labels that each got.

#1318 Allow cancel of the creation of an asynchronous service instance
  app/actions/services/locks/deleter_lock.rb
  app/actions/services/service_instance_delete.rb
  app/jobs/services/service_instance_state_fetch.rb
  lib/services/service_brokers/v2/client.rb
  lib/services/service_brokers/v2/response_parser.rb
  spec/acceptance/broker_api_compatibility/broker_api_v2.15_spec.rb
  spec/acceptance/broker_api_compatibility/broker_api_v2.9_spec.rb
  spec/acceptance/broker_api_compatibility/broker_api_versions_spec.rb
  spec/support/broker_api_helper.rb
  spec/unit/actions/services/locks/deleter_lock_spec.rb
  spec/unit/actions/services/service_instance_delete_spec.rb
  spec/unit/controllers/runtime/spaces_controller_spec.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/jobs/services/service_instance_state_fetch_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: sapi, unscheduled

#1321 Add service_broker_name for space summary endpoint.
  app/models/services/managed_service_instance.rb
  docs/v2/spaces/get_space_summary.html
  spec/request/v2/spaces_spec.rb
  spec/unit/models/services/managed_service_instance_spec.rb
Labels: sapi, scheduled

#1322 Add maintenance_info to the service plan
  app/models/services/service_plan.rb
  app/presenters/v2/service_plan_presenter.rb
  db/migrations/20190409110217_add_maintenance_info_to_service_plan.rb
  docs/v2/service_plans/retrieve_a_particular_service_plan.html
  lib/services/service_brokers/service_manager.rb
  lib/services/service_brokers/v2/catalog_plan.rb
  spec/acceptance/broker_api_compatibility/broker_api_v2.15_spec.rb
  spec/api/documentation/events_api_spec.rb
  spec/request/v2/service_plans_spec.rb
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
  spec/unit/lib/services/service_brokers/v2/catalog_plan_spec.rb
  spec/unit/models/services/service_plan_spec.rb
  spec/unit/presenters/v2/service_plan_presenter_spec.rb
Labels: in progress, sapi

#1324 Ability to trigger an update (of maintenance_info) on service instance
  app/actions/services/service_instance_update.rb
  app/controllers/services/service_instances_controller.rb
  app/controllers/services/validators/service_update_validator.rb
  app/models/services/service_plan.rb
  app/presenters/v2/service_plan_presenter.rb
  lib/services/service_brokers/v2/client.rb
  spec/acceptance/broker_api_compatibility/broker_api_v2.15_spec.rb
  spec/support/broker_api_helper.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/unit/actions/services/service_instance_update_spec.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/controllers/services/validators/service_update_validator_spec.rb
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  vendor/errors/v2.yml
Labels: unscheduled

#1325 Provide artifact name in droplet download action
  lib/cloud_controller/diego/buildpack/desired_lrp_builder.rb
  spec/unit/lib/cloud_controller/diego/buildpack/desired_lrp_builder_spec.rb
Labels: unscheduled

#1327 Add maintenance_info in update service instance api docs
  docs/v2/service_instances/update_a_service_instance.html
Labels: sapi, unscheduled

#1330 Implement stop_index method for the opi app client
  lib/cloud_controller/opi/apps_client.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
Labels: unscheduled
