Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-12, with the labels that each got.

#1502 Change label selector query logic to allow complex queries
  app/fetchers/app_revisions_fetcher.rb
  app/fetchers/domain_fetcher.rb
  app/fetchers/label_selector_query_generator.rb
  app/fetchers/route_fetcher.rb
  spec/request/routes_spec.rb
  spec/unit/fetchers/label_selector_query_generator_spec.rb
Labels: unscheduled

#1507 V3 service offerings get all 169341820
  app/controllers/v3/service_offerings_controller.rb
  app/fetchers/service_offering_fetcher.rb
  app/fetchers/service_offering_list_fetcher.rb
  config/routes.rb
  docs/v3/source/includes/api_resources/_service_offerings.erb
  docs/v3/source/includes/experimental_resources/service_offerings/_list.md.erb
  docs/v3/source/index.md
  lib/cloud_controller/perm/permissions.rb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/service_brokers_spec.rb
  spec/request/service_offerings_spec.rb
  spec/unit/fetchers/service_offering_fetcher_spec.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
  spec/unit/lib/perm/permissions_spec.rb
  spec/unit/lib/permissions/queryer_spec.rb
Labels: sapi, unscheduled

#1508 V3 delete broker 169596494
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  app/jobs/v3/services/update_broker_job.rb
  spec/request/service_brokers_spec.rb
  spec/unit/jobs/v3/synchronize_broker_catalog_job_spec.rb
  spec/unit/jobs/v3/update_broker_job_spec.rb
  vendor/errors/v3.yml
Labels: sapi, unscheduled

#1509 Add tests to most controllers for mixing query params and refactor label
  app/fetchers/app_list_fetcher.rb
  app/fetchers/build_list_fetcher.rb
  app/fetchers/domain_fetcher.rb
  app/fetchers/isolation_segment_list_fetcher.rb
  app/fetchers/label_selector_query_generator.rb
  app/fetchers/route_fetcher.rb
  app/fetchers/task_list_fetcher.rb
  spec/request/apps_spec.rb
  spec/request/buildpacks_spec.rb
  spec/request/builds_spec.rb
  spec/request/deployments_spec.rb
  spec/request/domains_spec.rb
  spec/request/droplets_spec.rb
  spec/request/isolation_segments_spec.rb
  spec/request/organizations_spec.rb
  spec/request/packages_spec.rb
  spec/request/processes_spec.rb
  spec/request/revisions_spec.rb
  spec/request/roles_spec.rb
  spec/request/routes_spec.rb
  spec/request/service_bindings_spec.rb
  spec/request/service_brokers_spec.rb
  spec/request/service_instances_spec.rb
  spec/request/sidecars_spec.rb
  spec/request/spaces_spec.rb
  spec/request/stacks_spec.rb
  spec/request/tasks_spec.rb
  spec/request/users_spec.rb
  spec/request_spec_shared_examples.rb
  spec/unit/fetchers/label_selector_query_generator_spec.rb
  spec/unit/fetchers/task_list_fetcher_spec.rb
Labels: unscheduled

#1511 Allow sending internal param with org relationship if set to false
  app/messages/domain_create_message.rb
  docs/v3/source/includes/resources/domains/_create.md.erb
  spec/request/domains_spec.rb
  spec/unit/messages/domain_create_message_spec.rb
Labels: unscheduled

#1519 V3 metadata broker 169543665
  app/actions/annotations_update.rb
  app/actions/labels_update.rb
  app/actions/metadata_update.rb
  app/actions/service_broker_create.rb
  app/actions/v3/service_broker_update.rb
  app/jobs/v3/services/update_broker_job.rb
  app/messages/service_broker_create_message.rb
  app/messages/service_broker_update_message.rb
  app/models.rb
  app/models/services/service_broker.rb
  app/models/services/service_broker_annotation_model.rb
  app/models/services/service_broker_label_model.rb
  app/models/services/service_broker_update_request.rb
  app/models/services/service_broker_update_request_annotation_model.rb
  app/models/services/service_broker_update_request_label_model.rb
  app/presenters/v3/service_broker_presenter.rb
  db/migrations/20191203153701_create_service_broker_metadata_tables.rb
  db/migrations/20191204144101_create_service_broker_update_request_metadata_tables.rb
  docs/v3/source/includes/api_resources/_service_offerings.erb
  spec/request/lifecycle/service_brokers_spec.rb
  spec/request/service_brokers_spec.rb
  spec/support/matchers/be_reported_as_events.rb
  spec/unit/actions/annotations_update_spec.rb
  spec/unit/actions/labels_update_spec.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
  spec/unit/jobs/v3/update_broker_job_spec.rb
  spec/unit/messages/service_broker_create_message_spec.rb
  spec/unit/messages/service_broker_update_message_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: sapi, unscheduled

#1524 Service offering should show only unique instances for public plans
  app/fetchers/service_offering_list_fetcher.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
Labels: sapi, unscheduled

#1525 GET /v3/service_brokers filtered by label_selector
  app/fetchers/service_broker_list_fetcher.rb
  app/messages/list_message.rb
  app/messages/service_brokers_list_message.rb
  spec/request/service_brokers_spec.rb
  spec/unit/fetchers/service_broker_list_fetcher_spec.rb
  spec/unit/messages/list_message_spec.rb
Labels: sapi
