Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2019-07, with the labels that each got.

#1383 Change MaintenanceInfoMismatch to MaintenanceInfoNotSupported
  app/controllers/services/validators/service_update_validator.rb
  spec/unit/controllers/services/validators/service_update_validator_spec.rb
  vendor/errors/v2.yml
Labels: sapi, unscheduled

#1385 Use fully qualified column names in DB query
  app/models/services/service_plan.rb
  spec/unit/controllers/services/service_plans_controller_spec.rb
Labels: review-requested, sapi, unscheduled

#1386 Enable space scoped service brokers for V3 API
  app/actions/service_broker_create.rb
  app/controllers/v3/service_brokers_controller.rb
  app/messages/service_broker_create_message.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/controllers/v3/service_brokers_controller_spec.rb
  spec/unit/messages/service_broker_create_message_spec.rb
Labels: sapi, unscheduled

#1387 Send maintenance_info on create service instance
  app/actions/services/service_instance_create.rb
  lib/services/service_brokers/v2/client.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/unit/actions/services/service_instance_create_spec.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: sapi, unscheduled

#1388 Upgrade Rubocop to latest version (0.72.0)
  .codeclimate.yml
  .rubocop.yml
  Gemfile.lock
  app/fetchers/add_route_fetcher.rb
  app/models/runtime/auto_detection_buildpack.rb
  app/models/runtime/buildpack.rb
  app/models/runtime/custom_buildpack.rb
  app/presenters/api/api_presenter.rb
  lib/cloud_controller/route_validator.rb
  lib/services/service_brokers/v2/schema.rb
  spec/acceptance/service_broker_spec.rb
  spec/unit/actions/service_instance_unshare_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/maintenance_info_conflict_spec.rb
Labels: unscheduled

#1394 Remove unused admin_buildpacks_presenter
  lib/cloud_controller.rb
  lib/cloud_controller/admin_buildpacks_presenter.rb
  spec/unit/lib/cloud_controller/admin_buildpack_presenter_spec.rb
Labels: unscheduled

#1395 Remove unused process_delete_fetcher
  app/fetchers/process_delete_fetcher.rb
  spec/unit/fetchers/process_delete_fetcher_spec.rb
Labels: unscheduled

#1356 Add configuration for thin thread pool size
  config/bosh-lite.yml
  config/cloud_controller.yml
  lib/cloud_controller/config_schemas/api_schema.rb
  lib/cloud_controller/runner.rb
  spec/fixtures/config/port_8181_config.yml
  spec/unit/lib/cloud_controller/config_spec.rb
Labels: unscheduled

#1392 Switch to Actual LRPS BBS endpoint
  lib/cloud_controller/diego/bbs_instances_client.rb
  lib/cloud_controller/diego/reporters/instances_reporter.rb
  lib/diego/actual_lrp_group_resolver.rb
  lib/diego/client.rb
  lib/diego/routes.rb
  spec/diego/actual_lrp_group_resolver_spec.rb
  spec/diego/client_spec.rb
  spec/request/v2/apps_spec.rb
  spec/unit/lib/cloud_controller/diego/bbs_instances_client_spec.rb
Labels: unscheduled

#1396 Upgrade fog-aliyun to 0.3.4
  Gemfile.lock
Labels: unscheduled

#1397 Remove references to app port from copilot
  Gemfile
  Gemfile.lock
  lib/cloud_controller/copilot/adapter.rb
  lib/cloud_controller/copilot/sync.rb
  spec/unit/actions/app_delete_spec.rb
  spec/unit/lib/cloud_controller/copilot/adapter_spec.rb
  spec/unit/lib/cloud_controller/copilot/sync_spec.rb
Labels: unscheduled
