Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-07, with the labels that each got.

#1711 Remove vendor directory
  .codeclimate.yml
  .rubocop.yml
  .solargraph.yml
  errors/v1.yml
  errors/v2.yml
  errors/v3.yml
  lib/cloud_controller/errors/details.rb
  lib/cloud_controller/errors/v3/details.rb
  spec/spec_helper.rb
  vendor/errors/README.md
Labels: unscheduled

#1720 v3(services): expose additional service instance fields
  app/decorators/field_service_instance_offering_decorator.rb
  app/messages/service_instance_show_message.rb
  app/messages/service_instances_list_message.rb
  docs/v3/source/includes/experimental_resources/service_instances/_get.md.erb
  docs/v3/source/includes/resources/service_instances/_list.md.erb
  spec/request/service_instances_spec.rb
  spec/unit/decorators/field_service_instance_offering_decorator_spec.rb
  spec/unit/messages/service_instance_show_message_spec.rb
  spec/unit/messages/service_instances_list_message_spec.rb
Labels: delivered, sapi

#1716 V2 apps return correct app guid in links
  app/controllers/runtime/apps_controller.rb
  app/presenters/v2/relations_presenter.rb
  spec/unit/controllers/runtime/apps_controller_spec.rb
Labels: unscheduled

#1717 V3 update async si 171670119
  app/jobs/v3/update_service_instance_job.rb
  docs/v3/source/includes/resources/service_instances/_update.md.erb
  spec/request/service_instances_spec.rb
  spec/support/shared_examples/jobs/service_instance_last_operation_polling_job.rb
  spec/unit/jobs/v3/create_service_instance_job_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: in progress, sapi

#1724 Fix task completion callback on k8s
  lib/cloud_controller/diego/task_completion_callback_generator.rb
  spec/unit/lib/cloud_controller/diego/task_completion_callback_generator_spec.rb
Labels: unscheduled

#1729 v3(services): deleting msi synchronously
  app/actions/v3/service_instance_delete.rb
  app/controllers/v3/service_instances_controller.rb
  app/jobs/v3/delete_service_instance_job.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
Labels: delivered, sapi

#1731 Make logcache tls optional
  lib/cloud_controller/config_schemas/api_schema.rb
  lib/logcache/client.rb
  spec/logcache/client_spec.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
Labels: unscheduled

#1733 v3(services): delete SI asynchronously
  app/actions/v3/service_instance_delete.rb
  app/jobs/v3/create_service_instance_job.rb
  app/jobs/v3/delete_service_instance_job.rb
  app/jobs/v3/service_instance_async_job.rb
  app/jobs/v3/update_service_instance_job.rb
  spec/request/service_instances_spec.rb
  spec/support/shared_examples/jobs/service_instance_async_job.rb
  spec/unit/jobs/v3/create_service_instance_job_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: delivered, sapi

#1735 v3(services): refactor async jobs tests
  app/jobs/v3/delete_service_instance_job.rb
  app/jobs/v3/service_instance_async_job.rb
  app/jobs/v3/update_service_instance_job.rb
  spec/support/shared_examples/jobs/service_instance_async_job.rb
  spec/unit/jobs/v3/create_service_instance_job_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
  spec/unit/jobs/v3/service_instance_async_job_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: unscheduled

#1736 fix(services): service instance create/update errors
  app/actions/service_instance_update_user_provided.rb
  app/controllers/v3/service_instances_controller.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_update_user_provided_spec.rb
Labels: delivered, sapi

#1740 Upgrade fog-aliyun to 0.3.17
  Gemfile.lock
Labels: in progress

#1624 Add github action for running tests
  .github/workflows/unit_tests.yml
Labels: in progress

#1738 v3(services): orphan mitigation when delete fails
  app/jobs/v3/delete_service_instance_job.rb
  app/jobs/v3/service_instance_async_job.rb
  lib/services/service_brokers/v2/response_parser.rb
  spec/request/service_instances_spec.rb
  spec/unit/jobs/services/service_instance_state_fetch_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
  spec/unit/jobs/v3/service_instance_async_job_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: sapi, unscheduled

#1746 Test docs in PRs
  .github/workflows/unit_tests.yml
Labels: unscheduled

#1748 Introduce .editorconfig for ruby files
  .editorconfig
Labels: in progress

#1749 v3(services): fix job state when deleting orphans
  app/jobs/pollable_job_wrapper.rb
  app/jobs/v3/delete_service_instance_job.rb
  spec/request/service_instances_spec.rb
  spec/unit/jobs/pollable_job_wrapper_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
Labels: in progress, sapi

#1750 v3(services): Return credential binding info for both key and app bindings
  app/controllers/v3/service_credential_bindings_controller.rb
  app/fetchers/service_credential_binding_fetcher.rb
  app/models.rb
  app/models/services/service_credential_binding_view.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_fetcher_spec.rb
Labels: delivered

#1754 v3(services): Add request test to ensure service credential binding sharing permissions
  spec/request/service_credential_bindings_spec.rb
Labels: delivered

#1758 v3(services): shared_spaces can include fields
  app/controllers/v3/service_instances_controller.rb
  app/decorators/field_service_instance_organization_decorator.rb
  app/decorators/field_service_instance_space_decorator.rb
  app/messages/shared_spaces_show_message.rb
  app/presenters/v3/to_many_relationship_presenter.rb
  docs/v3/source/includes/concepts/_fields.md.erb
  docs/v3/source/includes/resources/service_instances/_list_shared_spaces.md.erb
  spec/request/service_instances_spec.rb
  spec/unit/decorators/field_service_instance_organization_decorator_spec.rb
  spec/unit/decorators/field_service_instance_space_decorator_spec.rb
  spec/unit/messages/shared_spaces_show_message_spec.rb
  spec/unit/presenters/v3/service_instance_presenter_spec.rb
  spec/unit/presenters/v3/to_many_relationship_presenter_spec.rb
Labels: delivered, sapi

#1757 v3(services): allow SI's to be purged
  app/actions/service_instance_purge.rb
  app/controllers/v3/service_instances_controller.rb
  docs/v3/source/includes/experimental_resources/service_instances/_delete.md
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_purge_spec.rb
Labels: in progress, sapi

#1761 v3(services): Return list of service credential bindings
  .rspec
  app/controllers/v3/service_credential_bindings_controller.rb
  app/fetchers/service_credential_binding_fetcher.rb
  app/fetchers/service_credential_binding_list_fetcher.rb
  app/models/services/service_credential_binding_view.rb
  app/presenters/helpers/censorship.rb
  app/presenters/v3/base_presenter.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  config/routes.rb
  docs/v3/source/includes/api_resources/_service_credential_bindings.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_get.md.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_header.md
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  docs/v3/source/index.md
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_fetcher_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: delivered

#1763 properly audit all of message when creating service instance
  app/actions/service_instance_create_managed.rb
  app/jobs/v3/create_service_instance_job.rb
Labels: delivered
