Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-09, with the labels that each got.

#1815 v3(services): route binding last operation errors
  app/actions/service_route_binding_create.rb
  app/jobs/v3/create_route_binding_job.rb
  spec/request/service_route_bindings_spec.rb
  spec/unit/jobs/v3/create_route_binding_job_spec.rb
Labels: delivered

#1825 document kpack lifecycle
  docs/v3/source/includes/concepts/_lifecycles.md.erb
Labels: k8s

#1824 v3(services): Retry-After header type conversion
  app/jobs/v3/create_route_binding_job.rb
  app/jobs/v3/service_instance_async_job.rb
  spec/unit/jobs/v3/create_route_binding_job_spec.rb
  spec/unit/jobs/v3/service_instance_async_job_spec.rb
Labels: delivered

#1827 v3(services): order_by name for service offerings
  app/messages/service_offerings_list_message.rb
  docs/v3/source/includes/resources/service_offerings/_list.md.erb
  spec/request/service_offerings_spec.rb
  spec/request_spec_shared_examples.rb
  spec/unit/messages/service_offerings_list_message_spec.rb
Labels: in progress

#1828 v3(bindings): validations for UPSI ↔ App
  app/controllers/v3/service_credential_bindings_controller.rb
  app/messages/service_credential_binding_create_message.rb
  app/messages/service_credential_binding_list_message.rb
  app/messages/service_credential_binding_show_message.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_create.md.erb
  docs/v3/source/index.md
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
  spec/unit/messages/service_credential_binding_create_message_spec.rb
  spec/unit/messages/service_credential_binding_list_message_spec.rb
  spec/unit/messages/service_credential_binding_show_message_spec.rb
Labels: delivered

#1831 Unsharing a SI that is not shared should not fail
  app/controllers/v3/service_instances_controller.rb
  spec/request/service_instances_spec.rb
Labels: delivered

#1833 v3(bindings): UPSI can be bound to apps
  app/actions/service_credential_binding_create.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/models/services/service_binding.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/models/services/service_binding_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: in progress

#1832 filter service route bindings
  app/controllers/v3/service_route_bindings_controller.rb
  app/fetchers/route_binding_list_fetcher.rb
  app/messages/service_route_bindings_list_message.rb
  docs/v3/source/includes/experimental_resources/service_route_bindings/_list.md.erb
  spec/request/service_route_bindings_spec.rb
  spec/unit/fetchers/route_binding_list_fetcher_spec.rb
  spec/unit/messages/service_route_bindings_list_message_spec.rb
Labels: delivered

#1834 v3(bindings): delete bindings from UPSI
  app/actions/service_credential_binding_create.rb
  app/actions/service_credential_binding_delete.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/messages/service_credential_binding_create_message.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_delete.md
  docs/v3/source/includes/experimental_resources/service_instances/_delete.md
  docs/v3/source/index.md
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/actions/service_credential_binding_delete_spec.rb
  spec/unit/messages/service_credential_binding_create_message_spec.rb
Labels: delivered, sapi

#1841 v3(services): Add order_by created_at in view to make pagination
  app/models/services/service_credential_binding_view.rb
Labels: sapi, scheduled

#1844 emit pending/failed job metrics even when queue is empty
  lib/cloud_controller/metrics/periodic_updater.rb
  spec/unit/lib/cloud_controller/metrics/periodic_updater_spec.rb
Labels: k8s

#1849 v2/v3(services): remove orphan mitigation on async provisioning
  lib/services/service_brokers/v2/client.rb
  spec/request/service_instances_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: delivered, sapi

#1850 v3(service instance): allow metadata updates while create is in progress
  app/actions/service_instance_update_managed.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
Labels: in progress, sapi

#1851 v3(services): ensure MSI <=> app bindings are valid before creating
  app/actions/service_credential_binding_create.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  lib/services/service_brokers/service_client_provider.rb
  lib/services/service_brokers/user_provided/client.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/lib/services/service_brokers/user_provided/client_spec.rb
Labels: delivered

#1855 v3(test): route bindings orphan mitigation scenarios
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/request/bindings_orphan_mitigation.rb
Labels: delivered, sapi

#1856 v3(services): Respect plan max_polling_duration when creating route b…
  app/jobs/v3/create_route_binding_job.rb
  spec/unit/jobs/v3/create_route_binding_job_spec.rb
Labels: accepted, sapi

#1859 v3(bindings): create binding for MSI (sync)
  app/actions/service_credential_binding_create.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/jobs/v3/create_service_credential_binding_job.rb
  app/messages/service_credential_binding_create_message.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/jobs/v3/create_service_credential_binding_job_spec.rb
  spec/unit/messages/service_credential_binding_create_message_spec.rb
Labels: delivered, sapi

#1861 v3(services): update the platform broker poll interval while an async…
  app/jobs/reoccurring_job.rb
  spec/unit/jobs/reoccurring_job_spec.rb
Labels: delivered, sapi

#1863 v3(services): all bindings should have last_operation
  app/presenters/mixins/last_operation_helper.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  app/presenters/v3/service_route_binding_presenter.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
  spec/unit/presenters/v3/service_route_binding_presenter_spec.rb
Labels: delivered

#1862 v3(bindings): cant create bindings while SI operations are in progress
  app/actions/service_credential_binding_create.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
Labels: delivered

#1869 v3(bindings): fix audit logs for create bindings
  app/actions/service_credential_binding_create.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/jobs/v3/create_service_credential_binding_job.rb
  app/models/runtime/pollable_job_model.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/jobs/v3/create_service_credential_binding_job_spec.rb
  spec/unit/models/runtime/pollable_job_model_spec.rb
Labels: delivered

#1868 v3(services): delete a route binding **sync**
  app/actions/service_route_binding_delete.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/jobs/v3/delete_route_binding_job.rb
  config/routes.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/space_restricted_response_generators.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
  spec/unit/jobs/v3/delete_route_binding_job_spec.rb
Labels: delivered

#1873 v3(services): Update last_operation when job exceeds max_polling_dura…
  app/jobs/v3/create_route_binding_job.rb
  spec/unit/jobs/v3/create_route_binding_job_spec.rb
Labels: delivered, sapi

#1878 v3(services): delete route binding fixes
  app/actions/service_route_binding_delete.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_delete.md.erb
  docs/v3/source/includes/experimental_resources/service_route_bindings/_delete.md.erb
  docs/v3/source/index.md
  spec/unit/actions/service_route_binding_delete_spec.rb
Labels: delivered
