Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-12, with the labels that each got.

#1980 v3(services): refactor delete for service instance
  app/actions/v3/service_instance_delete.rb
  app/controllers/v3/service_instances_controller.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
Labels: scheduled

#1978 v3(services) GA service route bindings
  app/controllers/v3/root_controller.rb
  docs/v3/source/includes/resources/service_route_bindings/_create.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_delete.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_get.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_header.md
  docs/v3/source/includes/resources/service_route_bindings/_list.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_object.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_parameters.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_update.md.erb
  docs/v3/source/index.html.md
  spec/request/v3_root_spec.rb
Labels: delivered, sapi

#1983 v3(services): orphan mitigation for create key bindings failure
  app/jobs/v2/services/delete_orphaned_binding.rb
  lib/services/service_brokers/v2/client.rb
  spec/request/service_credential_bindings_spec.rb
  spec/support/shared_examples/request/bindings_create.rb
  spec/support/shared_examples/request/bindings_orphan_mitigation.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  spec/unit/lib/services/service_brokers/v2/orphan_mitigator_spec.rb
Labels: delivered, sapi

#1985 v3(services): refactor bindings models save methods
  app/actions/service_credential_binding_app_create.rb
  app/actions/service_credential_binding_key_create.rb
  app/actions/service_route_binding_create.rb
  app/actions/v3/service_binding_create.rb
  app/models/services/service_key.rb
  spec/unit/models/services/service_key_spec.rb
Labels: delivered

#1984 make credential_client_id optional when creating service keys
  lib/cloud_controller/config_schemas/api_schema.rb
  lib/services/service_brokers/v2/client.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: unscheduled

#1987 v3(services): add common filters to service credential bindings
  app/controllers/v3/service_credential_bindings_controller.rb
  app/fetchers/service_credential_binding_fetcher.rb
  app/fetchers/service_credential_binding_list_fetcher.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
Labels: delivered, sapi

#1988 v3(tests): add tests for service key last operation in response
  spec/request/service_credential_bindings_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: delivered, sapi

#1989 v3(services): add client config to worker
  lib/cloud_controller/config_schemas/base/worker_schema.rb
Labels: delivered, sapi

#1992 Stop action and actor from serialising in binding jobs
  app/jobs/v3/create_binding_async_job.rb
  app/jobs/v3/delete_binding_job.rb
Labels: delivered

#1991 v3(services): refactor delete service instance job
  app/actions/v3/service_instance_delete.rb
  app/controllers/v3/service_instances_controller.rb
  app/jobs/v3/delete_service_instance_job.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
Labels: in progress

#1996 V3 delete recursively user provided services
  app/actions/v3/service_instance_delete.rb
  app/controllers/v3/service_instances_controller.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
Labels: in progress

#1997 v3(tests): Add event log check to key bindings tests
  spec/request/service_credential_bindings_spec.rb
Labels: delivered, sapi

#2000 v3(tests): Create SI with v3 endpoint from service broker spec
  spec/request/service_brokers_spec.rb
Labels: sapi, scheduled

#1973 Change after_enqueue of enqueuer to before_enqueue and generate guid for delayed_job
  app/jobs/enqueuer.rb
  app/jobs/pollable_job_wrapper.rb
  app/jobs/wrapping_job.rb
  lib/cloud_controller.rb
  lib/delayed_job_plugins/before_enqueue_hook.rb
Labels: unscheduled

#1999 v3(docs): Improve examples for bindings
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_create.md.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_delete.md.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_object.md.erb
Labels: sapi, scheduled

#2002 v3(services): recursive delete of service instances
  app/actions/v3/service_instance_delete.rb
  app/controllers/v3/service_instances_controller.rb
  app/jobs/v3/delete_binding_job.rb
  docs/v3/source/includes/experimental_resources/service_instances/_delete.md.erb
  spec/request/service_instances_spec.rb
  spec/support/shared_examples/jobs/delete_binding_job.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
  spec/unit/controllers/runtime/stagings_controller_spec.rb
Labels: scheduled

#1995 Fix broken logging for cc_workers
  lib/cloud_controller/background_job_environment.rb
Labels: bug, unscheduled

#1826 Add link to the `get default domain` endpoint
  docs/v3/source/includes/resources/domains/_list_domains_for_an_org.md.erb
Labels: unscheduled

#1986 v3(docs): ADR for Orphan Mitigation in service bindings
  decisions/0009-services-bindings-orphan-mitigation.md
Labels: accepted, sapi
