Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-10, with the labels that each got.

#1884 v3(services): Change 'label' to 'name' in links for
  app/controllers/v3/service_offerings_controller.rb
  spec/request/service_offerings_spec.rb
Labels: delivered

#1889 v3(services) Added request tests for async app to service binding
  app/controllers/v3/service_credential_bindings_controller.rb
  spec/request/service_credential_bindings_spec.rb
Labels: delivered

#1881 v3(services): async delete route binding
  app/actions/service_route_binding_delete.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/jobs/v3/delete_route_binding_job.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/request/last_operation_response_handling.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
  spec/unit/jobs/v3/delete_route_binding_job_spec.rb
Labels: delivered

#1890 v3(service-plan-visibility): add audit events
  app/controllers/v3/service_plan_visibility_controller.rb
  app/repositories/service_event_repository.rb
  spec/request/service_plan_visibility_spec.rb
  spec/unit/repositories/service_event_repository_spec.rb
Labels: delivered

#1898 v3(service instance) Add links to bindings
  app/presenters/v3/service_instance_presenter.rb
  docs/v3/source/includes/api_resources/_service_instances.erb
  spec/request/service_instances_spec.rb
  spec/unit/presenters/v3/service_instance_presenter_spec.rb
Labels: delivered, hacktoberfest-accepted, sapi

#1896 v3(services): broker client to follow redirects
  lib/services/service_brokers/v2/http_client.rb
  spec/unit/lib/services/service_brokers/v2/http_client_spec.rb
Labels: delivered, sapi

#1897 V3 service credential bindings rework 174119280
  app/actions/service_credential_binding_create.rb
  app/actions/v3/service_binding_create.rb
  spec/request/service_credential_bindings_spec.rb
  spec/support/shared_examples/v3_service_binding_create.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
Labels: delivered

#1903 v3(services) Make sure the LO state is failed when job fails
  app/jobs/v3/create_binding_async_job.rb
  spec/support/shared_examples/jobs/create_binding_job.rb
Labels: in progress

#1904 v3(bindings): can create bindings with params
  app/models/services/service_binding.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/models/services/service_binding_spec.rb
Labels: delivered, hacktoberfest-accepted, sapi

#1908 v3(route bindings): fetch parameters
  app/controllers/v3/service_route_bindings_controller.rb
  app/presenters/v3/service_route_binding_presenter.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_parameters.md.erb
  docs/v3/source/includes/experimental_resources/service_route_bindings/_parameters.md.erb
  docs/v3/source/index.md
  spec/request/service_route_bindings_spec.rb
  spec/unit/presenters/v3/service_route_binding_presenter_spec.rb
Labels: delivered, hacktoberfest-accepted, sapi

#1909 fix docker app deletion when using a package registry
  app/actions/package_delete.rb
  app/jobs/runtime/delete_expired_package_blob.rb
  spec/unit/actions/package_delete_spec.rb
  spec/unit/jobs/runtime/delete_expired_package_blob_spec.rb
Labels: unscheduled

#1907 V3 last operation handle refactor
  app/actions/v3/service_binding_create.rb
  lib/services/service_brokers/v2/client.rb
  spec/support/shared_examples/jobs/create_binding_job.rb
  spec/support/shared_examples/request/last_operation_response_handling.rb
  spec/support/shared_examples/v3_service_binding_create.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/actions/service_route_binding_create_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: delivered

#1901 v2/v3(bindings): allow only one binding per app/SI
  db/migrations/20201013153721_add_service_instance_constraint_to_service_bindings.rb
Labels: sapi, scheduled

#1913 V3 handle last operation on unbind route service 174748133
  app/actions/service_route_binding_delete.rb
  app/jobs/v3/delete_route_binding_job.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/request/last_operation_response_handling.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
  spec/unit/jobs/v3/delete_route_binding_job_spec.rb
Labels: delivered

#1915 v2/v3(binding): use binding name on audit logs
  app/repositories/service_binding_event_repository.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/repositories/service_binding_event_repository_spec.rb
Labels: delivered, sapi

#1914 v3(bindings): orphan mitigation on create failures
  spec/request/service_credential_bindings_spec.rb
  spec/support/shared_examples/request/bindings_orphan_mitigation.rb
Labels: in progress, sapi

#1918 v3(binding): better message when unique constraint is violated
  app/actions/service_credential_binding_create.rb
  spec/support/shared_examples/v3_service_binding_create.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
Labels: delivered, sapi

#1917 Introduce "kpack" Droplets and Support Custom Start Commands
  app/actions/droplet_create.rb
  app/actions/droplet_update.rb
  app/models/runtime/droplet_model.rb
  app/presenters/v3/droplet_presenter.rb
  db/migrations/20201020204056_index_kpack_lifecycle_data_droplet_guid.rb
  lib/cloud_controller/kpack/stager.rb
  lib/cloud_controller/opi/apps_client.rb
  spec/support/fakes/blueprints.rb
  spec/unit/actions/droplet_create_spec.rb
  spec/unit/actions/droplet_update_spec.rb
  spec/unit/lib/cloud_controller/kpack/stager_spec.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
  spec/unit/models/runtime/droplet_model_spec.rb
  spec/unit/presenters/v3/droplet_presenter_spec.rb
Labels: hacktoberfest-accepted, k8s

#1920 v3(services): Broker provided operation is preserved in between last op polling
  app/actions/v3/service_binding_create.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/v3_service_binding_create.rb
Labels: in progress, sapi

#1929 v3(route-binding): delete when another operation is in progress
  app/actions/service_route_binding_delete.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/jobs/v3/delete_route_binding_job.rb
  lib/services/service_brokers/v2/client.rb
  spec/request/service_route_bindings_spec.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: delivered, sapi

#1930 v3(services): Unbind - broker operation is passed in every LO request
  app/actions/service_route_binding_delete.rb
  spec/request/service_route_bindings_spec.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
  spec/unit/jobs/v3/delete_route_binding_job_spec.rb
Labels: delivered

#1892 Implement get and list methods for tasks in OPI
  lib/cloud_controller/opi/task_client.rb
  spec/unit/lib/cloud_controller/opi/task_client_spec.rb
Labels: unscheduled

#1932 Update README.md to reflect VM/k8s deployments
  README.md
Labels: unscheduled

#1933 test: combine methods of testing metadata
  spec/request/app_manifests_spec.rb
  spec/request/deployments_spec.rb
  spec/request/service_instances_spec.rb
  spec/request/space_manifests_spec.rb
  spec/support/matchers/contain_metadata.rb
  spec/support/matchers/have_annotations.rb
  spec/support/matchers/have_labels.rb
  spec/unit/actions/app_create_spec.rb
  spec/unit/actions/app_update_spec.rb
  spec/unit/actions/build_create_spec.rb
  spec/unit/actions/build_update_spec.rb
  spec/unit/actions/deployment_create_spec.rb
  spec/unit/actions/deployment_update_spec.rb
  spec/unit/actions/domain_create_spec.rb
  spec/unit/actions/domain_update_spec.rb
  spec/unit/actions/droplet_update_spec.rb
  spec/unit/actions/organization_create_spec.rb
  spec/unit/actions/package_update_spec.rb
  spec/unit/actions/process_update_spec.rb
  spec/unit/actions/revisions_update_spec.rb
  spec/unit/actions/route_update_spec.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
  spec/unit/actions/service_instance_update_user_provided_spec.rb
  spec/unit/actions/space_create_spec.rb
  spec/unit/actions/stack_create_spec.rb
  spec/unit/actions/stack_update_spec.rb
  spec/unit/actions/task_create_spec.rb
  spec/unit/actions/task_update_spec.rb
  spec/unit/actions/transactional_metadata_update_spec.rb
  spec/unit/actions/user_create_spec.rb
  spec/unit/actions/user_update_spec.rb
  spec/unit/controllers/v3/organizations_controller_spec.rb
  spec/unit/controllers/v3/packages_controller_spec.rb
  spec/unit/controllers/v3/spaces_controller_spec.rb
  spec/unit/controllers/v3/stacks_controller_spec.rb
  spec/unit/isolation_segment_create_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: delivered

#1921 Add basic Honeycomb instrumentation
  Gemfile
  Gemfile.lock
  config/initializers/honeycomb.rb
  lib/cloud_controller/config_schemas/api_schema.rb
  lib/cloud_controller/rack_app_builder.rb
Labels: unscheduled
