Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-08, with the labels that each got.

#1765 v3(services): usage summary on shared spaces
  app/controllers/v3/service_instances_controller.rb
  app/presenters/v3/shared_spaces_usage_summary_presenter.rb
  config/routes.rb
  docs/v3/source/includes/api_resources/_service_instances.erb
  docs/v3/source/includes/experimental_resources/service_instances/_get_shared_spaces_usage_summary.md.erb
  docs/v3/source/index.md
  spec/request/service_instances_spec.rb
  spec/unit/presenters/v3/shared_spaces_usage_summary_presenter_spec.rb
Labels: delivered, sapi

#1766 v3(services): Filter SI by Org guid
  app/controllers/v3/service_instances_controller.rb
  app/fetchers/service_instance_list_fetcher.rb
  app/messages/service_instances_list_message.rb
  docs/v3/source/includes/resources/service_instances/_list.md.erb
  spec/request/service_instances_spec.rb
  spec/unit/fetchers/service_instance_list_fetcher_spec.rb
  spec/unit/messages/service_instances_list_message_spec.rb
Labels: delivered, sapi

#1769 v3(services): GET credential binding object response
  app/fetchers/service_credential_binding_fetcher.rb
  app/models/services/service_credential_binding_view.rb
  app/presenters/v3/base_presenter.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  docs/v3/source/includes/api_resources/_service_credential_bindings.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_fetcher_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: delivered, sapi

#1771 v3(services): cred binding list body
  app/models/services/service_credential_binding_view.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  docs/v3/source/includes/api_resources/_service_credential_bindings.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_fetcher_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: accepted

#1776 Refactor service_instance_update_managed to use Method Object pattern
  app/actions/service_instance_update_managed.rb
Labels: accepted

#1777 v3(services): don't redact in audit logs for empty credentials/params
  app/messages/service_instance_create_user_provided_message.rb
  app/repositories/service_event_repository.rb
  spec/api/documentation/events_api_spec.rb
  spec/lightweight_spec_helper.rb
  spec/unit/messages/service_instance_create_user_provided_message_spec.rb
  spec/unit/repositories/service_event_repository_spec.rb
Labels: delivered

#1779 v3(services): audit whole request body when updating service async
  app/actions/service_instance_update_managed.rb
  app/jobs/v3/update_service_instance_job.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
Labels: delivered

#1780 v3(services): only redact credentials when updating upsi when actually provided
  app/messages/metadata_base_message.rb
  app/messages/service_instance_create_message.rb
  app/messages/service_instance_create_user_provided_message.rb
  app/messages/service_instance_message.rb
  app/messages/service_instance_update_user_provided_message.rb
  spec/unit/messages/service_instance_update_user_provided_message_spec.rb
Labels: delivered, sapi

#1783 v3(services): use original name as target when auditing update si events
  app/actions/service_instance_update_managed.rb
  app/actions/service_instance_update_user_provided.rb
  app/jobs/v3/service_instance_async_job.rb
  app/jobs/v3/update_service_instance_job.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
  spec/unit/actions/service_instance_update_user_provided_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: delivered

#1785 v3(services): credential binding filters
  app/controllers/v3/service_credential_bindings_controller.rb
  app/fetchers/service_credential_binding_list_fetcher.rb
  app/messages/service_credential_bindings_list_message.rb
  app/models/services/service_credential_binding_view.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
  spec/unit/messages/service_credential_bindings_list_message_spec.rb
Labels: delivered, sapi

#1786 v3(services): null for request when recording si delete audit event
  app/actions/v3/service_instance_delete.rb
  app/jobs/v3/delete_service_instance_job.rb
  app/repositories/service_event_repository.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
  spec/unit/repositories/service_event_repository_spec.rb
Labels: delivered

#1789 v3(services): introduce service route binding endpoint
  app/controllers/v3/service_route_bindings_controller.rb
  app/messages/service_route_binding_create_message.rb
  config/routes.rb
  spec/request/service_route_bindings_spec.rb
  spec/unit/messages/service_route_binding_create_message_spec.rb
Labels: delivered

#1792 Service instance sharing tests
  app/actions/service_instance_share.rb
  app/controllers/v3/service_instances_controller.rb
  config/routes.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_share_spec.rb
  spec/unit/controllers/v3/service_instances_controller_spec.rb
Labels: delivered

#1794 v3(bindings): allow the binding app to be included
  app/controllers/v3/service_credential_bindings_controller.rb
  app/decorators/include_binding_app_decorator.rb
  app/messages/service_credential_bindings_list_message.rb
  app/messages/service_credential_bindings_show_message.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_get.md.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/decorators/include_binding_app_decorator_spec.rb
  spec/unit/messages/service_credential_bindings_list_message_spec.rb
  spec/unit/messages/service_credential_bindings_show_message_spec.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: delivered, sapi

#1791 v3(services): Add service creation to synoptic lifecycle test
  spec/request/lifecycle/services_synoptic_spec.rb
Labels: delivered

#1795 v3(bindings): allow the binding SI to be included
  app/controllers/v3/service_credential_bindings_controller.rb
  app/decorators/include_binding_service_instance_decorator.rb
  app/messages/service_credential_bindings_list_message.rb
  app/messages/service_credential_bindings_show_message.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_get.md.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/decorators/include_binding_app_decorator_spec.rb
  spec/unit/decorators/include_binding_service_instance_decorator_spec.rb
  spec/unit/messages/service_credential_bindings_list_message_spec.rb
  spec/unit/messages/service_credential_bindings_show_message_spec.rb
Labels: delivered, sapi

#1797 v3(services): test order_by for services resources
  app/controllers/v3/service_credential_bindings_controller.rb
  app/messages/apps_list_message.rb
  app/messages/isolation_segments_list_message.rb
  app/messages/orgs_list_message.rb
  app/messages/service_brokers_list_message.rb
  app/messages/service_credential_bindings_list_message.rb
  app/messages/service_instances_list_message.rb
  app/messages/service_plans_list_message.rb
  app/messages/spaces_list_message.rb
  app/messages/stacks_list_message.rb
  docs/v3/source/includes/resources/service_plans/_list.md.erb
  spec/request/service_brokers_spec.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_instances_spec.rb
  spec/request/service_offerings_spec.rb
  spec/request/service_plans_spec.rb
  spec/request_spec_shared_examples.rb
  spec/support/shared_examples/request/service_brokers.rb
  spec/unit/messages/service_credential_bindings_list_message_spec.rb
  spec/unit/messages/service_instances_list_message_spec.rb
  spec/unit/messages/service_plans_list_message_spec.rb
Labels: delivered

#1801 v3(bindings): resolve credhub refs for keys
  app/controllers/v3/service_credential_bindings_controller.rb
  app/presenters/v3/service_credential_binding_details_presenter.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/presenters/v3/service_credential_binding_details_presenter_spec.rb
Labels: sapi, scheduled

#1806 v3(services): route binding to managed service instance
  app/actions/service_route_binding_create.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/jobs/v3/services/create_route_binding_job.rb
  app/messages/service_route_binding_create_message.rb
  docs/v3/source/includes/experimental_resources/service_route_bindings/_create.md.erb
  spec/request/service_route_bindings_spec.rb
  spec/unit/actions/service_route_binding_create_spec.rb
  spec/unit/messages/service_route_binding_create_message_spec.rb
Labels: in progress

#1808 v3(bindings): add plan and offering filters
  app/fetchers/service_credential_binding_list_fetcher.rb
  app/messages/service_credential_bindings_list_message.rb
  app/models/services/service_credential_binding_view.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
  spec/unit/messages/service_credential_bindings_list_message_spec.rb
Labels: delivered, sapi

#1812 v3(services): route binding show 'route_service_url'
  app/presenters/v3/service_route_binding_presenter.rb
  docs/v3/source/includes/api_resources/_service_route_bindings.erb
  docs/v3/source/includes/experimental_resources/service_route_bindings/_object.md.erb
  spec/request/service_route_bindings_spec.rb
  spec/unit/presenters/v3/service_route_binding_presenter_spec.rb
Labels: delivered

#1811 v3(services): route binding respect Retry-After header
  app/actions/service_route_binding_create.rb
  app/jobs/v3/create_route_binding_job.rb
  spec/unit/actions/service_route_binding_create_spec.rb
  spec/unit/jobs/v3/create_route_binding_job_spec.rb
Labels: delivered

#1787 Add audit events for Apps#show_env and Revisions#show_environment_variables
  app/controllers/v3/apps_controller.rb
  app/controllers/v3/revisions_controller.rb
  app/repositories/app_event_repository.rb
  app/repositories/revision_event_repository.rb
  spec/unit/controllers/v3/apps_controller_spec.rb
  spec/unit/controllers/v3/revisions_controller_spec.rb
Labels: enhancement, scheduled
