Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-11, with the labels that each got.

#1935 docs(services): parameters for service credential binding
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_create.md.erb
Labels: delivered

#1941 v3(services): filter route bindings by labels
  app/fetchers/route_binding_list_fetcher.rb
  app/messages/service_route_bindings_list_message.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/fakes/blueprints.rb
  spec/unit/fetchers/route_binding_list_fetcher_spec.rb
  spec/unit/messages/service_route_bindings_list_message_spec.rb
Labels: delivered, sapi

#1942 V3 unbind service credential binding sync and async
  app/actions/service_credential_binding_delete.rb
  app/actions/service_route_binding_delete.rb
  app/actions/v3/service_binding_create.rb
  app/actions/v3/service_binding_delete.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/jobs/v3/delete_binding_job.rb
  app/jobs/v3/delete_service_binding_job_factory.rb
  app/jobs/v3/delete_service_credential_binding_job_actor.rb
  app/jobs/v3/delete_service_route_binding_job_actor.rb
  app/messages/service_route_bindings_list_message.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/jobs/delete_binding_job.rb
  spec/support/shared_examples/v3_service_binding_delete.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/actions/service_credential_binding_delete_spec.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
  spec/unit/jobs/v3/delete_binding_job_spec.rb
  spec/unit/jobs/v3/delete_route_binding_job_spec.rb
  spec/unit/jobs/v3/delete_service_binding_job_factory_spec.rb
  spec/unit/jobs/v3/delete_service_route_binding_job_actor_spec.rb
  spec/unit/messages/service_route_bindings_list_message_spec.rb
Labels: delivered, sapi

#1623 Remove experimental tag from includes
  docs/v3/source/includes/resources/apps/_get.md.erb
  docs/v3/source/includes/resources/apps/_list.md.erb
  docs/v3/source/includes/resources/roles/_get.md.erb
  docs/v3/source/includes/resources/roles/_list.md.erb
  docs/v3/source/includes/resources/routes/_get.md.erb
  docs/v3/source/includes/resources/routes/_list.md.erb
  docs/v3/source/includes/resources/spaces/_get_a_space.md.erb
  docs/v3/source/includes/resources/spaces/_list.md.erb
Labels: unscheduled

#1622 Remove experimental tag from label selectors
  docs/v3/source/includes/experimental_resources/revisions/_list.md.erb
  docs/v3/source/includes/resources/apps/_list.md.erb
  docs/v3/source/includes/resources/buildpacks/_list.md.erb
  docs/v3/source/includes/resources/builds/_list.md.erb
  docs/v3/source/includes/resources/builds/_list_for_app.md.erb
  docs/v3/source/includes/resources/deployments/_list.md.erb
  docs/v3/source/includes/resources/domains/_list.md.erb
  docs/v3/source/includes/resources/domains/_list_domains_for_an_org.md.erb
  docs/v3/source/includes/resources/droplets/_list.md.erb
  docs/v3/source/includes/resources/droplets/_list_for_app.md.erb
  docs/v3/source/includes/resources/droplets/_list_for_package.md.erb
  docs/v3/source/includes/resources/isolation_segments/_list.md.erb
  docs/v3/source/includes/resources/organizations/_list.md.erb
  docs/v3/source/includes/resources/packages/_list.md.erb
  docs/v3/source/includes/resources/processes/_list.md.erb
  docs/v3/source/includes/resources/processes/_list_for_app.md.erb
  docs/v3/source/includes/resources/routes/_list.md.erb
  docs/v3/source/includes/resources/routes/_list_for_app.md.erb
  docs/v3/source/includes/resources/service_brokers/_list.md.erb
  docs/v3/source/includes/resources/service_instances/_list.md.erb
  docs/v3/source/includes/resources/service_offerings/_list.md.erb
  docs/v3/source/includes/resources/service_plans/_list.md.erb
  docs/v3/source/includes/resources/spaces/_list.md.erb
  docs/v3/source/includes/resources/stacks/_list.md.erb
  docs/v3/source/includes/resources/tasks/_list.md.erb
  docs/v3/source/includes/resources/tasks/_list_for_app.md.erb
  docs/v3/source/includes/resources/users/_list.md.erb
Labels: unscheduled

#1515 Remove deployment state from API
  app/presenters/v3/deployment_presenter.rb
  docs/v3/source/includes/api_resources/_deployments.erb
  docs/v3/source/includes/resources/deployments/_object.md.erb
  spec/request/deployments_spec.rb
  spec/unit/presenters/v3/deployment_presenter_spec.rb
Labels: unscheduled

#1944 Revert "Implement get and list methods for tasks in OPI"
  lib/cloud_controller/opi/task_client.rb
  spec/unit/lib/cloud_controller/opi/task_client_spec.rb
Labels: unscheduled

#1943 v3(route-bindings): fail the create job when a delete starts
  app/jobs/v3/create_binding_async_job.rb
  spec/support/shared_examples/jobs/create_binding_job.rb
Labels: delivered, sapi

#1945 V3 add audit events for route bindings 175228173
  app/actions/service_credential_binding_create.rb
  app/actions/service_credential_binding_delete.rb
  app/actions/service_route_binding_create.rb
  app/actions/service_route_binding_delete.rb
  app/actions/v3/service_binding_create.rb
  app/actions/v3/service_binding_delete.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/jobs/v3/create_service_binding_job_factory.rb
  app/jobs/v3/delete_service_binding_job_factory.rb
  app/repositories/service_generic_binding_event_repository.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/unit/actions/service_credential_binding_create_spec.rb
  spec/unit/actions/service_credential_binding_delete_spec.rb
  spec/unit/actions/service_route_binding_create_spec.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
Labels: delivered

#1948 v3(services): Allow bind from shared spaces
  app/controllers/v3/service_credential_bindings_controller.rb
  spec/request/service_credential_bindings_spec.rb
Labels: delivered, sapi

#1938 Upgrade middleman et al. for v3 docs
  .gitignore
  docs/v3/Gemfile
  docs/v3/Gemfile.lock
  docs/v3/config.rb
  docs/v3/source/includes/api_resources/_security_groups.erb
  docs/v3/source/index.html.md
  docs/v3/source/layouts/layout.erb
  docs/v3/source/stylesheets/_normalize.scss
  docs/v3/source/stylesheets/_syntax.scss.erb
  docs/v3/source/stylesheets/print.css.scss
  docs/v3/source/stylesheets/screen.css.scss
Labels: dependencies, unscheduled

#1925 Update fog-azure-rm to enable fog debug
  Gemfile.lock
Labels: unscheduled

#1955 v3(services): eager load for instances endpoint
  app/controllers/v3/service_instances_controller.rb
  app/fetchers/service_instance_list_fetcher.rb
  app/presenters/v3/service_instance_presenter.rb
  spec/request/service_instances_spec.rb
  spec/unit/fetchers/service_instance_list_fetcher_spec.rb
Labels: delivered

#1951 v3(services): binding request spec shared examples
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
Labels: delivered

#1960 Remove app apply manifest endpoint
  app/actions/space_diff_manifest.rb
  app/controllers/v3/app_manifests_controller.rb
  app/controllers/v3/apps_controller.rb
  app/controllers/v3/space_manifests_controller.rb
  app/jobs/app_apply_manifest_action_job.rb
  app/messages/app_manifest_message.rb
  app/messages/named_app_manifest_message.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/app_manifest/_apply.md
  docs/v3/source/includes/experimental_resources/app_manifest/_header.md
  docs/v3/source/includes/experimental_resources/app_manifest/_object.md.erb
  docs/v3/source/includes/experimental_resources/sidecars/_header.md
  docs/v3/source/index.html.md
  lib/cloud_controller/jobs.rb
  spec/request/app_manifests_spec.rb
  spec/unit/actions/app_find_or_create_skeleton_spec.rb
  spec/unit/controllers/v3/app_manifests_controller_spec.rb
  spec/unit/jobs/app_apply_manifest_action_job_spec.rb
  spec/unit/jobs/space_apply_manifest_action_job_spec.rb
  spec/unit/messages/app_manifest_message_spec.rb
  spec/unit/messages/named_app_manifest_message_spec.rb
Labels: in progress

#1963 App restart action is no longer experimental
  docs/v3/source/includes/experimental_resources/app_restart/_header.md
  docs/v3/source/includes/resources/apps/_restart.md.erb
  docs/v3/source/index.html.md
Labels: unscheduled

#1966 v3(services) Return validation of quotas for service key creation
  app/actions/mixins/service_credential_binding_validation_create.rb
  app/actions/service_credential_binding_key_create.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/actions/service_credential_binding_key_create_spec.rb
Labels: delivered, sapi

#1967 v3(tests): lifecycle tests for service route bindings
  spec/request/lifecycle/service_route_bindings_synoptic_spec.rb
Labels: delivered, sapi

#1971 v3(docs): Add service route bindings to upgrade guide
  docs/v3/source/includes/experimental_resources/service_route_bindings/_header.md
  docs/v3/source/includes/upgrade_guide/changed_resources/_service_instance_routes_in_v3.md
  docs/v3/source/includes/upgrade_guide/new_resources/_service_route_bindings.md
  docs/v3/source/index.html.md
Labels: delivered, sapi

#1972 v3(services): add common filters to service route bindings resource
  app/controllers/v3/service_route_bindings_controller.rb
  app/fetchers/route_binding_list_fetcher.rb
  docs/v3/source/includes/experimental_resources/service_route_bindings/_list.md.erb
  spec/request/service_route_bindings_spec.rb
  spec/unit/fetchers/route_binding_list_fetcher_spec.rb
Labels: delivered, sapi

#1975 use TCPServer for rake-task readiness checks
  lib/cloud_controller/background_job_environment.rb
  spec/unit/lib/background_job_environment_spec.rb
Labels: unscheduled
