Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-06, with the labels that each got.

#1626 Remove service broker url from error responses
  lib/cloud_controller/http_response_error.rb
  lib/services/service_brokers/v2/errors/app_required.rb
  lib/services/service_brokers/v2/errors/async_required.rb
  lib/services/service_brokers/v2/errors/concurrency_error.rb
  lib/services/service_brokers/v2/errors/maintenance_info_conflict.rb
  lib/services/service_brokers/v2/errors/service_broker_api_authentication_failed.rb
  lib/services/service_brokers/v2/errors/service_broker_bad_response.rb
  lib/services/service_brokers/v2/errors/service_broker_conflict.rb
  lib/services/service_brokers/v2/errors/service_broker_invalid_syslog_drain_url.rb
  lib/services/service_brokers/v2/errors/service_broker_invalid_volume_mounts.rb
  lib/services/service_brokers/v2/errors/service_broker_request_rejected.rb
  lib/services/service_brokers/v2/errors/service_broker_response_malformed.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/space_delete_spec.rb
  spec/unit/controllers/runtime/organizations_controller_spec.rb
  spec/unit/controllers/runtime/spaces_controller_spec.rb
  spec/unit/jobs/services/service_binding_state_fetch_spec.rb
  spec/unit/jobs/services/service_instance_state_fetch_spec.rb
  spec/unit/jobs/v3/create_service_instance_job_spec.rb
  spec/unit/lib/http_response_error_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/app_required_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/async_required_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_api_authentication_failed_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_bad_response_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_conflict_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_request_rejected_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_response_malformed_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: sapi, unscheduled

#1679 Update experimental flag for services endpoints in /v3 root
  app/controllers/v3/root_controller.rb
  spec/request/v3_root_spec.rb
Labels: sapi, unscheduled

#1693 fix(services): orphan mitigation only for create
  lib/services/service_brokers/v2/client.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: accepted, sapi

#1588 Implement the OPI task client
  app/actions/task_create.rb
  lib/cloud_controller/dependency_locator.rb
  lib/cloud_controller/diego/bbs_task_client.rb
  lib/cloud_controller/opi/task_client.rb
  spec/unit/actions/task_create_spec.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
  spec/unit/lib/cloud_controller/diego/bbs_task_client_spec.rb
  spec/unit/lib/cloud_controller/opi/task_client_spec.rb
Labels: scheduled

#1699 V3 maintenance info noop 171702179
  app/actions/service_instance_update_managed.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
Labels: in progress, sapi

#1704 v3(services): improve quotas error message
  app/actions/mixins/service_instance_create.rb
  app/actions/service_instance_create_managed.rb
  app/controllers/v3/service_instances_controller.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_create_managed_spec.rb
Labels: in progress, sapi

#1708 v3(services): delete user-provided SI
  app/actions/service_instance_delete_user_provided.rb
  app/controllers/v3/service_instances_controller.rb
  app/models/services/service_instance.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_instances/_delete.md
  docs/v3/source/index.md
  lib/cloud_controller/errors/api_error.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_delete_user_provided_spec.rb
  spec/unit/lib/cloud_controller/errors/api_error_spec.rb
  spec/unit/models/services/service_instance_spec.rb
Labels: in progress, sapi
