Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2020-01, with the labels that each got.

#1528 Send staging task resource requests to OPI
  lib/cloud_controller/opi/stager_client.rb
  spec/unit/lib/cloud_controller/opi/stager_client_spec.rb
Labels: unscheduled

#1536 Doc: service brokers label selector
  docs/v3/source/includes/experimental_resources/service_brokers/_list.md.erb
Labels: sapi, unscheduled

#1535 As a /v3 API user, I want to GET a list of service offerings that are available
  app/controllers/v3/service_offerings_controller.rb
  app/fetchers/service_offering_list_fetcher.rb
  app/messages/service_offerings_list_message.rb
  docs/v3/source/includes/experimental_resources/service_offerings/_list.md.erb
  spec/request/service_offerings_spec.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
  spec/unit/messages/service_offerings_list_message_spec.rb
Labels: sapi, unscheduled

#1537 V3 filter service offerings by service broker GUID
  app/fetchers/service_offering_list_fetcher.rb
  app/messages/service_offerings_list_message.rb
  docs/v3/source/includes/experimental_resources/service_offerings/_list.md.erb
  spec/request/service_offerings_spec.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
  spec/unit/messages/service_offerings_list_message_spec.rb
Labels: sapi, unscheduled

#1538 Add link to service offerings from service broker read and list response
  app/presenters/v3/service_broker_presenter.rb
  docs/v3/source/includes/api_resources/_service_brokers.erb
  spec/request/service_brokers_spec.rb
  spec/unit/presenters/v3/service_broker_presenter_spec.rb
Labels: sapi, unscheduled

#1540 V3 filter service offerings by service broker names
  app/fetchers/service_offering_list_fetcher.rb
  app/messages/service_offerings_list_message.rb
  docs/v3/source/includes/experimental_resources/service_offerings/_list.md.erb
  spec/request/service_offerings_spec.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
  spec/unit/messages/service_offerings_list_message_spec.rb
Labels: sapi, unscheduled

#1541 V3 Service plans get and list - support feature flag `hide_marketplace_f…
  app/controllers/v3/root_controller.rb
  app/controllers/v3/service_plans_controller.rb
  app/fetchers/service_plan_list_fetcher.rb
  app/presenters/v3/service_plan_presenter.rb
  config/routes.rb
  spec/request/service_plans_spec.rb
  spec/request/v3_root_spec.rb
  spec/unit/fetchers/service_plan_list_fetcher_spec.rb
  spec/unit/presenters/v3/service_plan_presenter_spec.rb
Labels: sapi, unscheduled

#1543 Improve formatting of service deactivation warning message
  lib/services/service_brokers/service_manager.rb
  spec/acceptance/service_broker_spec.rb
  spec/request/service_brokers_spec.rb
  spec/unit/lib/services/service_brokers/service_manager_spec.rb
Labels: sapi, unscheduled

#1544 Update service_offering object
  app/presenters/v3/service_offering_presenter.rb
  docs/v3/source/includes/api_resources/_service_offerings.erb
  docs/v3/source/includes/experimental_resources/service_offerings/_object.md.erb
  docs/v3/source/index.md
  spec/request/service_offerings_spec.rb
  spec/unit/presenters/v3/service_offering_presenter_spec.rb
Labels: sapi

#1517 Add link to an app's features
  app/presenters/v3/app_presenter.rb
  docs/v3/source/includes/api_resources/_apps.erb
  spec/request/apps_spec.rb
  spec/request/stacks_spec.rb
  spec/unit/presenters/v3/app_presenter_spec.rb
Labels: unscheduled

#1518 App ssh enabled is no longer experimental
  docs/v3/source/includes/experimental_resources/app_ssh_enabled/_header.md
  docs/v3/source/includes/resources/apps/_ssh_enabled.md.erb
  docs/v3/source/index.md
Labels: unscheduled

#1514 Deployments are no longer experimental
  app/controllers/v3/root_controller.rb
  docs/v3/source/includes/resources/deployments/_cancel.md.erb
  docs/v3/source/includes/resources/deployments/_create.md.erb
  docs/v3/source/includes/resources/deployments/_get.md.erb
  docs/v3/source/includes/resources/deployments/_header.md
  docs/v3/source/includes/resources/deployments/_list.md.erb
  docs/v3/source/includes/resources/deployments/_object.md.erb
  docs/v3/source/includes/resources/deployments/_update.md.erb
  docs/v3/source/index.md
  spec/request/v3_root_spec.rb
Labels: unscheduled

#1516 App Features are no longer experimental
  docs/v3/source/includes/experimental_resources/app_features/_header.md
  docs/v3/source/includes/resources/app_features/_get.md.erb
  docs/v3/source/includes/resources/app_features/_header.md
  docs/v3/source/includes/resources/app_features/_list.md.erb
  docs/v3/source/includes/resources/app_features/_object.md.erb
  docs/v3/source/includes/resources/app_features/_supported_features.md.erb
  docs/v3/source/includes/resources/app_features/_update.md.erb
  docs/v3/source/index.md
Labels: unscheduled

#1512 Enable a second symmetric key to enable key rotation in UAA
  lib/cloud_controller/config_schemas/api_schema.rb
  lib/cloud_controller/uaa/uaa_token_decoder.rb
  spec/unit/lib/uaa/uaa_token_decoder_spec.rb
Labels: in progress

#1530 Propagate prometheus annotations to opi
  lib/cloud_controller/opi/apps_client.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
Labels: unscheduled

#1546 Send more info to staging tasks created by OPI
  lib/cloud_controller/opi/stager_client.rb
  spec/unit/lib/cloud_controller/opi/stager_client_spec.rb
Labels: unscheduled

#1549 Fixed Annotations with prefixed keys not being removed
  app/actions/annotations_update.rb
  spec/request/lifecycle/service_brokers_spec.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/annotations_update_spec.rb
  spec/unit/actions/labels_update_spec.rb
  spec/unit/actions/service_instance_update_spec.rb
Labels: sapi, unscheduled

#1550 Implement GET /v3/service_plans
  app/models/services/service_plan.rb
  app/presenters/v3/service_offering_presenter.rb
  app/presenters/v3/service_plan_presenter.rb
  docs/v3/source/includes/api_resources/_service_plans.erb
  docs/v3/source/includes/experimental_resources/service_plans/_header.md
  docs/v3/source/includes/experimental_resources/service_plans/_list.md.erb
  docs/v3/source/includes/experimental_resources/service_plans/_object.md.erb
  docs/v3/source/index.md
  spec/request/service_plans_spec.rb
  spec/unit/models/services/service_plan_spec.rb
  spec/unit/presenters/v3/service_offering_presenter_spec.rb
  spec/unit/presenters/v3/service_plan_presenter_spec.rb
Labels: sapi, unscheduled

#1551 Implement PATCH for service offerings
  app/actions/service_offering_update.rb
  app/controllers/v3/service_offerings_controller.rb
  app/fetchers/service_offering_list_fetcher.rb
  app/messages/service_offering_update_message.rb
  app/models.rb
  app/models/services/service.rb
  app/models/services/service_offering_annotation_model.rb
  app/models/services/service_offering_label_model.rb
  app/presenters/v3/service_offering_presenter.rb
  config/routes.rb
  db/migrations/20200121104723_create_service_offering_metadata.rb
  docs/v3/source/includes/api_resources/_service_offerings.erb
  docs/v3/source/includes/experimental_resources/service_brokers/_update.md.erb
  docs/v3/source/includes/experimental_resources/service_offerings/_list.md.erb
  docs/v3/source/includes/experimental_resources/service_offerings/_update.md.erb
  docs/v3/source/index.md
  spec/request/service_brokers_spec.rb
  spec/request/service_offerings_spec.rb
  spec/support/fakes/blueprints.rb
  spec/support/matchers/contain_metadata.rb
  spec/unit/actions/service_offering_update_spec.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
  spec/unit/presenters/v3/service_offering_presenter_spec.rb
Labels: sapi, unscheduled

#1552 Make sure V2 endpoints can delete service offerings, brokers, instances
  app/models/services/service.rb
  app/models/services/service_broker.rb
  app/models/services/service_instance.rb
  spec/unit/models/services/service_broker_spec.rb
  spec/unit/models/services/service_instance_spec.rb
  spec/unit/models/services/service_spec.rb
Labels: sapi, unscheduled
