Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-08, with the labels that each got.

#2450 Remove unnecessary select from users table
  lib/cloud_controller/security/security_context_configurer.rb
Labels: unscheduled

#2338 Log when DB queries return large numbers of rows
  lib/cloud_controller/config_schemas/base/api_schema.rb
  lib/cloud_controller/db.rb
  spec/unit/lib/cloud_controller/db_dataset_spec.rb
Labels: scheduled

#2374 Allow space application supporter to access specific service binding …
  app/controllers/v3/service_credential_bindings_controller.rb
  docs/v3/source/includes/resources/service_credential_bindings/_create.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_delete.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_details.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_get.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_list.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_parameters.md.erb
  spec/request/service_credential_bindings_spec.rb
Labels: unscheduled, space-application-supporter

#2413 Retry polling on broker errors in V3
  app/actions/v3/service_instance_create_managed.rb
  spec/unit/actions/v3/service_instance_create_managed_spec.rb
Labels: unscheduled

#2449 Improve isolation segments performance
  app/controllers/v3/domains_controller.rb
  app/controllers/v3/isolation_segments_controller.rb
  app/controllers/v3/organizations_controller.rb
  lib/cloud_controller/permissions.rb
  spec/support/user_helpers.rb
  spec/unit/controllers/v3/isolation_segments_controller_spec.rb
  spec/unit/controllers/v3/tasks_controller_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: unscheduled

#2443 Wrap all errors in delete_non_transactional_subresources
  app/actions/app_delete.rb
  spec/unit/actions/app_delete_spec.rb
Labels: unscheduled

#2439 Add route destinations protocols
  app/actions/update_route_destinations.rb
  app/controllers/v3/routes_controller.rb
  app/messages/route_update_destinations_message.rb
  app/models/runtime/route.rb
  app/models/runtime/route_mapping_model.rb
  app/presenters/v3/route_destination_presenter.rb
  db/migrations/20210715232228_add_http_version_to_route_mappings.rb
  docs/v3/source/includes/api_resources/_routes.erb
  docs/v3/source/includes/resources/routes/_destination_object.md.erb
  docs/v3/source/includes/resources/routes/_insert_destinations.md.erb
  docs/v3/source/includes/resources/routes/_replace_destinations.md.erb
  lib/cloud_controller/diego/app_recipe_builder.rb
  lib/cloud_controller/diego/protocol/routing_info.rb
  spec/request/route_destinations_spec.rb
  spec/request/routes_spec.rb
  spec/support/fakes/blueprints.rb
  spec/unit/actions/update_route_destinations_spec.rb
  spec/unit/lib/cloud_controller/diego/app_recipe_builder_spec.rb
  spec/unit/lib/cloud_controller/diego/protocol/routing_info_spec.rb
  spec/unit/messages/route_update_destinations_message_spec.rb
  spec/unit/models/runtime/route_mapping_model_spec.rb
  spec/unit/models/runtime/route_spec.rb
  spec/unit/presenters/v3/route_destination_presenter_spec.rb
  spec/unit/presenters/v3/route_destinations_presenter_spec.rb
  spec/unit/presenters/v3/route_presenter_spec.rb
Labels: unscheduled

#2467 Prevent users with space supporter role reaching v2 endpoints
  docs/v3/source/includes/resources/roles/_valid_roles.md.erb
  lib/cloud_controller/rack_app_builder.rb
  middleware/block_v3_only_roles.rb
  spec/request/v2/auth_spec.rb
Labels: unscheduled
