Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-06, with the labels that each got.

#2300 Allow space application supporter to access specific domain endpoints
  app/controllers/v3/apps_controller.rb
  app/controllers/v3/domains_controller.rb
  app/controllers/v3/roles_controller.rb
  app/controllers/v3/spaces_controller.rb
  docs/v3/source/includes/resources/domains/_get.md.erb
  docs/v3/source/includes/resources/organizations/_get_default_domain.md.erb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/apps_spec.rb
  spec/request/domains_spec.rb
  spec/request/organizations_spec.rb
  spec/request/roles_spec.rb
  spec/request/spaces_spec.rb
  spec/support/user_helpers.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: unscheduled

#2305 Allow space application supporter to access specific app POST endpoints
  app/controllers/v3/apps_controller.rb
  docs/v3/source/includes/resources/apps/_restart.md.erb
  docs/v3/source/includes/resources/apps/_start.md.erb
  docs/v3/source/includes/resources/apps/_stop.md.erb
  spec/request/apps_spec.rb
  spec/support/user_helpers.rb
Labels: unscheduled

#2314 Space application supporter /v3/spaces endpoint permissions
  app/controllers/v3/space_features_controller.rb
  app/controllers/v3/spaces_controller.rb
  docs/v3/package-lock.json
  docs/v3/source/includes/resources/audit_events/_list.md.erb
  docs/v3/source/includes/resources/deployments/_list.md.erb
  docs/v3/source/includes/resources/domains/_get.md.erb
  docs/v3/source/includes/resources/organizations/_get_default_domain.md.erb
  docs/v3/source/includes/resources/routes/_check_route_reservations.md.erb
  docs/v3/source/includes/resources/routes/_create.md.erb
  docs/v3/source/includes/resources/routes/_delete.md.erb
  docs/v3/source/includes/resources/routes/_delete_unmapped.md.erb
  docs/v3/source/includes/resources/routes/_get.md.erb
  docs/v3/source/includes/resources/routes/_insert_destinations.md.erb
  docs/v3/source/includes/resources/routes/_list_destinations.md.erb
  docs/v3/source/includes/resources/routes/_list_for_app.md.erb
  docs/v3/source/includes/resources/routes/_remove_destination.md.erb
  docs/v3/source/includes/resources/routes/_replace_destinations.md.erb
  docs/v3/source/includes/resources/routes/_update.md.erb
  docs/v3/source/includes/resources/space_features/_get.md.erb
  docs/v3/source/includes/resources/space_features/_list.md.erb
  docs/v3/source/includes/resources/spaces/_get_a_space.md.erb
  docs/v3/source/includes/resources/spaces/get_assigned_isolation_segment.md.erb
  docs/v3/source/includes/resources/tasks/_get.md.erb
  docs/v3/source/includes/resources/tasks/_list_for_app.md.erb
  docs/v3/source/includes/resources/users/_get.md.erb
  spec/request/space_features_spec.rb
  spec/request/spaces_spec.rb
  spec/request_spec_shared_examples.rb
  spec/unit/controllers/v3/spaces_controller_spec.rb
Labels: space-application-supporter, unscheduled

#2307 docs: update service instance list intro
  docs/v3/source/includes/resources/service_instances/_list.md.erb
Labels: unscheduled

#2322 Use a consistent format for roles table notes in API docs
  docs/v3/source/includes/resources/domains/_get.md.erb
  docs/v3/source/includes/resources/organizations/_get_default_domain.md.erb
  docs/v3/source/includes/resources/service_brokers/_delete.md.erb
  docs/v3/source/includes/resources/service_brokers/_get.md.erb
  docs/v3/source/includes/resources/service_brokers/_list.md.erb
  docs/v3/source/includes/resources/service_brokers/_update.md.erb
  docs/v3/source/includes/resources/service_offerings/_delete.md.erb
  docs/v3/source/includes/resources/service_offerings/_update.md.erb
  docs/v3/source/includes/resources/service_plans/_delete.md.erb
  docs/v3/source/includes/resources/service_plans/_update.md.erb
  docs/v3/source/includes/resources/space_features/_get.md.erb
  docs/v3/source/includes/resources/space_features/_list.md.erb
  docs/v3/source/includes/resources/spaces/_get_a_space.md.erb
  docs/v3/source/includes/resources/spaces/get_assigned_isolation_segment.md.erb
  docs/v3/source/includes/resources/users/_get.md.erb
  docs/v3/source/includes/resources/users/_list.md.erb
Labels: unscheduled

#2324 Allow Space Application Supporter access to specific Audit Events endpoints
  app/controllers/v3/events_controller.rb
  docs/v3/source/includes/resources/audit_events/_get.md.erb
  docs/v3/source/includes/resources/audit_events/_list.md.erb
  docs/v3/source/includes/resources/users/_list.md.erb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/events_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: space-application-supporter

#2316 Ensure that space application supporter can access GET /v3/jobs/:guid
  docs/v3/source/includes/resources/jobs/_get.md.erb
  spec/request/jobs_spec.rb
Labels: space-application-supporter, unscheduled

#2317 Ensure that space application supporter can access user GET endpoints
  docs/v3/source/includes/resources/users/_get.md.erb
  docs/v3/source/includes/resources/users/_list.md.erb
  spec/request/users_spec.rb
Labels: space-application-supporter, unscheduled

#2319 Ensure that space application supporter can get/list buildpacks
  spec/request/buildpacks_spec.rb
Labels: space-application-supporter, unscheduled

#2325 Space application supporter can access environment variable groups
  spec/request/environment_variable_groups_spec.rb
Labels: space-application-supporter

#2328 Space application supporter can get and list packages
  app/controllers/v3/packages_controller.rb
  docs/v3/source/includes/resources/packages/_get.md.erb
  docs/v3/source/includes/resources/packages/_list_for_app.md.erb
  spec/request/packages_spec.rb
  spec/support/model_creation.rb
  spec/support/user_helpers.rb
Labels: space-application-supporter, unscheduled

#2334 Allow space application supporter to access specific droplet endpoints
  app/controllers/v3/droplets_controller.rb
  docs/v3/source/includes/resources/droplets/_get.md.erb
  docs/v3/source/includes/resources/droplets/_list_for_app.md.erb
  docs/v3/source/includes/resources/droplets/_list_for_package.md.erb
  spec/request/droplets_spec.rb
  spec/unit/controllers/v3/droplets_controller_spec.rb
Labels: space-application-supporter, unscheduled

#2347 Prove that all roles can get and list stacks
  spec/request/stacks_spec.rb
Labels: space-application-supporter, unscheduled

#2356 Remove `unmunged_body` method and references
  app/controllers/v3/application_controller.rb
  app/controllers/v3/organizations_controller.rb
  app/controllers/v3/processes_controller.rb
Labels: unscheduled

#2329 Log caller and query length for sql queries
  lib/cloud_controller/db.rb
  lib/sequel/extensions/query_length_logging.rb
  spec/unit/lib/sequel/extensions/query_length_logging_spec.rb
Labels: scheduled
