Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-01, with the labels that each got.

#2029 v3(services): deny subsequent delete binding request
  app/actions/v3/service_binding_delete.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/controllers/v3/service_route_bindings_controller.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/v3_service_binding_delete.rb
  spec/unit/actions/service_credential_binding_delete_spec.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
Labels: in progress

#2030 v3(services) Add binding and instance id to VCAP_SERVICES
  app/presenters/system_environment/service_binding_presenter.rb
  docs/v3/source/includes/resources/apps/_env.md.erb
  spec/request/apps_spec.rb
  spec/request/service_bindings_spec.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
  spec/unit/presenters/system_environment/service_binding_presenter_spec.rb
Labels: delivered

#2034 v3(services): unbind error should include app name
  app/actions/services/route_binding_delete.rb
  app/actions/v3/service_instance_delete.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
Labels: delivered

#2035 v3(services): use v3 code path for space delete
  app/actions/space_delete.rb
  app/controllers/services/lifecycle/service_instance_deprovisioner.rb
  app/models/runtime/route.rb
  spec/unit/actions/space_delete_spec.rb
Labels: scheduled

#2031 V3 service cred binding metadata 174260138
  app/actions/service_credential_binding_app_create.rb
  app/actions/service_credential_binding_key_create.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/messages/service_credential_binding_create_message.rb
  app/models.rb
  app/models/services/service_binding.rb
  app/models/services/service_binding_annotation_model.rb
  app/models/services/service_binding_label_model.rb
  app/models/services/service_key.rb
  app/models/services/service_key_annotation_model.rb
  app/models/services/service_key_label_model.rb
  db/migrations/20210105151532_create_service_bindings_metadata_tables.rb
  db/migrations/20210106120645_create_service_keys_metadata_tables.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_create.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/support/shared_examples/request/bindings_create.rb
  spec/unit/actions/service_credential_binding_app_create_spec.rb
  spec/unit/actions/service_credential_binding_key_create_spec.rb
  spec/unit/messages/service_credential_binding_create_message_spec.rb
Labels: scheduled

#2037 v3(services) Retrieve metadata for single credential bindings endpoint
  app/presenters/v3/service_credential_binding_presenter.rb
  docs/v3/source/includes/api_resources/_service_credential_bindings.erb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_object.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/support/fakes/blueprints.rb
  spec/unit/presenters/v3/service_credential_binding_presenter_spec.rb
Labels: delivered

#2038 V3 delete metadata from service cred binding 174260622
  spec/request/service_credential_bindings_spec.rb
  spec/unit/models/services/service_binding_spec.rb
  spec/unit/models/services/service_key_spec.rb
Labels: delivered

#2041 v3(services): synchronous broker name and metadata updates
  app/actions/v3/service_broker_update.rb
  app/controllers/v3/service_brokers_controller.rb
  docs/v3/source/includes/resources/service_brokers/_update.md.erb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
Labels: delivered

#2046 v3(services): revert synchronous broker name updates
  app/actions/v3/service_broker_update.rb
  spec/request/service_brokers_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
Labels: scheduled

#2045 v3(services) Filter service credential bindings by label
  app/fetchers/service_credential_binding_list_fetcher.rb
  app/messages/service_credential_binding_list_message.rb
  app/models/services/service_credential_binding_view.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_list.md.erb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
  spec/unit/messages/service_credential_binding_list_message_spec.rb
Labels: scheduled

#2043 v3(services): incorrect binding example in docs
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_create.md.erb
Labels: delivered

#1998 Update fog-azure-rm
  Gemfile.lock
Labels: dependencies, unscheduled

#2052 Modified kpack lifecycle run commands.
  lib/cloud_controller/opi/apps_client.rb
  spec/unit/lib/cloud_controller/opi/apps_client_spec.rb
Labels: unscheduled

#2050 services: do not expose broker URL in binding errors
  lib/services/service_brokers/v2/errors/http_client_timeout.rb
  lib/services/service_brokers/v2/errors/service_broker_api_timeout.rb
  lib/services/service_brokers/v2/errors/service_broker_api_unreachable.rb
  lib/services/service_brokers/v2/errors/service_broker_conflict.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_api_timeout_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_api_unreachable_spec.rb
  spec/unit/lib/services/service_brokers/v2/errors/service_broker_conflict_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: delivered

#2047 v3(services): update broker name not sync catalog
  app/jobs/v3/services/update_broker_job.rb
  docs/v3/source/includes/resources/service_brokers/_update.md.erb
  spec/unit/jobs/v3/services/update_broker_job_spec.rb
Labels: delivered

#2051 v3(services): reject binding parameters for user-provided service
  app/controllers/v3/service_credential_bindings_controller.rb
  app/controllers/v3/service_route_bindings_controller.rb
  spec/request/service_credential_bindings_spec.rb
Labels: delivered

#2058 v3(tests): fix flaky test
  spec/request/service_credential_bindings_spec.rb
Labels: delivered, sapi

#2059 v3(services): update metadata for a binding
  app/controllers/v3/service_credential_bindings_controller.rb
  config/routes.rb
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_update.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_update.md.erb
  docs/v3/source/index.html.md
  spec/request/service_bindings_shared_examples.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
Labels: delivered

#2061 Added audit logging when SI update includes metadata update only
  app/actions/service_instance_update_managed.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
Labels: delivered

#2060 v3(service) document changes of service instances in v3 vs v2
  docs/v3/source/includes/resources/service_instances/_header.md
  docs/v3/source/includes/resources/service_instances/_update.md.erb
  docs/v3/source/includes/upgrade_guide/changed_resources/_service_instance_route_bindings_in_v3.md
  docs/v3/source/includes/upgrade_guide/changed_resources/_service_instances_in_v3.md
  docs/v3/source/includes/upgrade_guide/conceptual_changes/_asynchronous_operations.md
  docs/v3/source/index.html.md
Labels: delivered

#2007 Staging no longer requires process types
  lib/cloud_controller/diego/staging_completion_handler.rb
  spec/unit/controllers/internal/staging_completion_controller_spec.rb
  spec/unit/lib/cloud_controller/diego/buildpack/staging_completion_handler_spec.rb
  spec/unit/lib/cloud_controller/diego/docker/staging_completion_handler_spec.rb
Labels: enhancement, unscheduled

#2065 v3(services): service broker client can take user_guid
  app/actions/service_binding_delete.rb
  app/actions/services/database_error_service_resource_cleanup.rb
  app/actions/v3/service_binding_delete.rb
  app/jobs/v2/services/delete_orphaned_binding.rb
  lib/services/service_brokers/v2/client.rb
  lib/services/service_brokers/v2/http_client.rb
  spec/support/shared_examples/v3_service_binding_delete.rb
  spec/unit/actions/app_delete_spec.rb
  spec/unit/actions/service_binding_delete_spec.rb
  spec/unit/actions/services/database_error_service_resource_cleanup_spec.rb
  spec/unit/jobs/services/delete_orphaned_binding_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  spec/unit/lib/services/service_brokers/v2/http_client_spec.rb
Labels: delivered

#2064 v3(services): GA Service Instances
  app/controllers/v3/root_controller.rb
  docs/v2/index.html
  docs/v3/source/includes/experimental_resources/service_instances/_header.md
  docs/v3/source/includes/resources/service_instances/_create.md.erb
  docs/v3/source/includes/resources/service_instances/_credentials.md.erb
  docs/v3/source/includes/resources/service_instances/_delete.md.erb
  docs/v3/source/includes/resources/service_instances/_get.md.erb
  docs/v3/source/includes/resources/service_instances/_get_shared_spaces_usage_summary.md.erb
  docs/v3/source/includes/resources/service_instances/_list.md.erb
  docs/v3/source/includes/resources/service_instances/_list_shared_spaces.md.erb
  docs/v3/source/includes/resources/service_instances/_object.md.erb
  docs/v3/source/includes/resources/service_instances/_parameters.md.erb
  docs/v3/source/includes/resources/service_instances/_update.md.erb
  docs/v3/source/index.html.md
  spec/request/v3_root_spec.rb
Labels: delivered

#2066 v3(services): send ID header with create, update broker
  app/actions/service_broker_create.rb
  app/actions/v3/service_broker_update.rb
  app/controllers/v3/service_brokers_controller.rb
  app/jobs/v3/services/service_broker_catalog_updater.rb
  app/jobs/v3/services/synchronize_broker_catalog_job.rb
  app/jobs/v3/services/update_broker_job.rb
  spec/request/service_brokers_spec.rb
  spec/support/fakes/fake_service_broker_v2_client.rb
  spec/unit/actions/service_broker_create_spec.rb
  spec/unit/actions/v3/service_broker_update_spec.rb
  spec/unit/jobs/pollable_job_wrapper_spec.rb
  spec/unit/jobs/v3/services/synchronize_broker_catalog_job_spec.rb
  spec/unit/jobs/v3/services/update_broker_job_spec.rb
  spec/unit/lib/services/service_brokers/v2/http_client_spec.rb
Labels: delivered

#2069 v3(services): send ID header with CRUD instance
  app/actions/v3/service_instance_delete.rb
  app/controllers/v3/service_instances_controller.rb
  app/jobs/v3/create_service_instance_job.rb
  app/jobs/v3/service_instance_async_job.rb
  app/jobs/v3/update_service_instance_job.rb
  spec/request/service_instances_spec.rb
  spec/support/background_job_helpers.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
  spec/unit/jobs/v3/create_service_instance_job_spec.rb
  spec/unit/jobs/v3/service_instance_async_job_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: in progress

#2070 v3(services) Document upgrade guide for service credential bindings
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_header.md
  docs/v3/source/includes/experimental_resources/service_credential_bindings/_object.md.erb
  docs/v3/source/includes/upgrade_guide/changed_resources/_service_bindings_in_v3.md
  docs/v3/source/includes/upgrade_guide/conceptual_changes/_asynchronous_operations.md
  docs/v3/source/index.html.md
Labels: delivered

#2076 v3(services) GA Service Credential Bindings
  app/controllers/v3/root_controller.rb
  docs/v2/index.html
  docs/v3/source/includes/resources/service_credential_bindings/_create.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_delete.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_details.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_get.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_header.md
  docs/v3/source/includes/resources/service_credential_bindings/_list.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_object.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_parameters.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_update.md.erb
  docs/v3/source/includes/upgrade_guide/changed_resources/_service_bindings_in_v3.md
  docs/v3/source/includes/upgrade_guide/conceptual_changes/_asynchronous_operations.md
  docs/v3/source/index.html.md
  spec/request/v3_root_spec.rb
Labels: delivered

#2071 v3(services): send ID header with CRD for bindings
  app/actions/v3/service_binding_create.rb
  app/actions/v3/service_binding_delete.rb
  lib/services/service_brokers/user_provided/client.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/request/bindings_create.rb
  spec/support/shared_examples/v3_service_binding_create.rb
  spec/support/shared_examples/v3_service_binding_delete.rb
  spec/unit/actions/service_credential_binding_app_create_spec.rb
  spec/unit/actions/service_credential_binding_delete_spec.rb
  spec/unit/actions/service_credential_binding_key_create_spec.rb
  spec/unit/actions/service_route_binding_create_spec.rb
  spec/unit/actions/service_route_binding_delete_spec.rb
Labels: delivered

#2068 Deal with kpack lifecycle tasks when desiring tasks
  lib/cloud_controller/opi/task_client.rb
  spec/unit/lib/cloud_controller/opi/task_client_spec.rb
Labels: unscheduled

#2077 v3(docs) Document migration path from space summary to using fields.
  docs/v3/source/includes/concepts/_fields.md.erb
  docs/v3/source/includes/upgrade_guide/conceptual_changes/_resource_summaries.md
Labels: delivered

#1934 Prevent unnecessary retries in the LRP instances client
  lib/cloud_controller/opi/instances_client.rb
  spec/unit/lib/cloud_controller/opi/instances_client_spec.rb
Labels: k8s, unscheduled

#2078 v3(tests): Space-scoped brokers should not be writable in suspended …
  spec/request/service_brokers_spec.rb
  spec/support/shared_examples/request/suspended_orgs_permissions.rb
Labels: delivered, sapi

#2083 Eirini LRP instances client can handle processes with 0 instances
  lib/cloud_controller/opi/instances_client.rb
  spec/unit/lib/cloud_controller/opi/instances_client_spec.rb
Labels: k8s, unscheduled

#2081 v3(services): service plan eager loading
  app/controllers/v3/service_plans_controller.rb
  app/fetchers/service_plan_list_fetcher.rb
  app/presenters/v3/service_plan_presenter.rb
  spec/request/service_plans_spec.rb
  spec/unit/fetchers/service_instance_list_fetcher_spec.rb
  spec/unit/fetchers/service_plan_list_fetcher_spec.rb
Labels: delivered

#2082 v3(services): optimize service plan presenter
  app/presenters/v3/service_plan_presenter.rb
Labels: scheduled

#2086 v3(services): service offerings eager loading
  app/controllers/v3/service_offerings_controller.rb
  app/fetchers/base_service_list_fetcher.rb
  app/fetchers/service_offering_list_fetcher.rb
  app/fetchers/service_plan_list_fetcher.rb
  app/presenters/v3/service_offering_presenter.rb
  spec/request/service_offerings_spec.rb
  spec/unit/fetchers/service_offering_list_fetcher_spec.rb
  spec/unit/presenters/v3/service_offering_presenter_spec.rb
Labels: delivered

#2084 v3(services): shared spaces link for service instances response
  app/presenters/v3/service_instance_presenter.rb
  docs/v3/source/includes/api_resources/_service_instances.erb
  spec/request/service_instances_spec.rb
  spec/unit/presenters/v3/service_instance_presenter_spec.rb
Labels: delivered

#2090 V3 cf push service binding refactor 176654281
  app/actions/app_apply_manifest.rb
  app/actions/service_credential_binding_app_create.rb
  app/actions/service_credential_binding_key_create.rb
  app/actions/service_route_binding_create.rb
  app/actions/v3/service_binding_create.rb
  spec/request/space_manifests_spec.rb
  spec/support/shared_examples/v3_service_binding_create.rb
  spec/unit/actions/app_apply_manifest_spec.rb
  spec/unit/actions/service_credential_binding_app_create_spec.rb
  spec/unit/actions/service_credential_binding_key_create_spec.rb
  spec/unit/actions/service_route_binding_create_spec.rb
Labels: in progress

#2091 v3(services): route binding delete permissions
  app/controllers/v3/service_route_bindings_controller.rb
  spec/support/space_restricted_response_generators.rb
Labels: delivered, sapi

#2085 v3(services): service broker eager loading
  app/controllers/v3/service_brokers_controller.rb
  app/fetchers/service_broker_list_fetcher.rb
  spec/request/service_brokers_spec.rb
  spec/unit/fetchers/service_broker_list_fetcher_spec.rb
Labels: delivered

#2092 v3(docs): Document service key behaviiour on unshare
  docs/v3/source/includes/resources/service_instances/_unshare_from_space.md.erb
Labels: delivered

#2088 v3(services): service route binding eager loading
  app/controllers/v3/service_route_bindings_controller.rb
  app/fetchers/route_binding_list_fetcher.rb
  app/presenters/v3/service_route_binding_presenter.rb
  spec/request/service_route_bindings_spec.rb
  spec/unit/fetchers/route_binding_list_fetcher_spec.rb
Labels: delivered
