Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-02, with the labels that each got.

#2097 services: catalog validation for duplicate plan IDs
  lib/services/service_brokers/v2/catalog.rb
  lib/services/service_brokers/v2/catalog_service.rb
  spec/acceptance/service_broker_spec.rb
  spec/unit/lib/services/service_brokers/v2/catalog_service_spec.rb
Labels: delivered

#2096 V3 consistent service broker permissions 176595049
  app/controllers/v3/service_brokers_controller.rb
  spec/request/service_brokers_spec.rb
  spec/support/space_restricted_response_generators.rb
Labels: delivered, sapi

#2093 v3(services): service credential bindings eager loading
  app/controllers/v3/service_credential_bindings_controller.rb
  app/fetchers/service_credential_binding_list_fetcher.rb
  app/models/services/service_credential_binding_view.rb
  app/models/services/service_instance.rb
  app/presenters/v3/service_credential_binding_presenter.rb
  spec/models/services/service_credential_binding_view_spec.rb
  spec/request/service_credential_bindings_spec.rb
  spec/unit/fetchers/service_credential_binding_list_fetcher_spec.rb
Labels: delivered

#2101 v3(services) Introduce last operation for user-provided si
  app/actions/service_instance_create_user_provided.rb
  app/actions/service_instance_update_user_provided.rb
  app/models/services/managed_service_instance.rb
  app/models/services/service_instance.rb
  app/models/services/user_provided_service_instance.rb
  app/presenters/v3/service_instance_presenter.rb
  docs/v3/source/includes/api_resources/_service_instances.erb
  docs/v3/source/includes/resources/service_instances/_object.md.erb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_create_user_provided_spec.rb
  spec/unit/actions/service_instance_purge_spec.rb
  spec/unit/actions/service_instance_update_user_provided_spec.rb
  spec/unit/actions/v3/service_instance_delete_spec.rb
  spec/unit/models/services/user_provided_service_instance_spec.rb
  spec/unit/presenters/v3/service_instance_presenter_spec.rb
Labels: delivered

#2105 Temporarily revert: Retry logic for fetching instance info from Eirini
  lib/cloud_controller/opi/instances_client.rb
  spec/unit/lib/cloud_controller/opi/instances_client_spec.rb
Labels: unscheduled

#2103 Added telemetry for service credential binding
  app/actions/service_credential_binding_app_create.rb
  spec/request/service_credential_bindings_spec.rb
Labels: delivered

#2102 v3(tests): suspended organization test scenarios and refactor
  spec/request/service_instances_spec.rb
Labels: delivered, sapi

#2104 v3(services): test cred binding perms for shared spaces when org suspended
  spec/request/service_credential_bindings_spec.rb
Labels: delivered

#2109 perf: eager loading in decorators
  app/decorators/include_binding_app_decorator.rb
  app/decorators/include_binding_route_decorator.rb
  app/decorators/include_binding_service_instance_decorator.rb
  app/decorators/include_organization_decorator.rb
  app/decorators/include_role_organization_decorator.rb
  app/decorators/include_role_space_decorator.rb
  app/decorators/include_role_user_decorator.rb
  app/decorators/include_route_domain_decorator.rb
  app/decorators/include_service_plan_service_offering_decorator.rb
  app/decorators/include_service_plan_space_organization_decorator.rb
  app/decorators/include_space_decorator.rb
  app/decorators/include_space_organization_decorator.rb
Labels: scheduled

#2112 v3(services): eager loading in service plan presenter
  app/presenters/v3/service_plan_presenter.rb
  spec/request/service_plans_spec.rb
Labels: accepted, sapi

#2108 services: validate binding credentials
  lib/services/service_brokers/v2/response_parser.rb
  spec/unit/controllers/services/lifecycle/service_instance_binding_manager_spec.rb
  spec/unit/lib/services/service_brokers/v2/response_parser_spec.rb
Labels: delivered

#2106 V3 refactor service instance create
  app/actions/mixins/service_instance_create.rb
  app/actions/service_instance_create_managed.rb
  app/actions/service_instance_update_managed.rb
  app/actions/v3/service_instance_create_managed.rb
  app/actions/v3/service_instance_update_managed.rb
  app/controllers/v3/service_instances_controller.rb
  app/jobs/v3/create_service_instance_job.rb
  app/jobs/v3/delete_service_instance_job.rb
  app/jobs/v3/service_instance_async_job.rb
  app/jobs/v3/update_service_instance_job.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/service_instance_create_managed_spec.rb
  spec/unit/actions/service_instance_create_user_provided_spec.rb
  spec/unit/actions/service_instance_update_managed_spec.rb
  spec/unit/actions/service_instance_update_user_provided_spec.rb
  spec/unit/actions/services/service_instance_create_managed_spec.rb
  spec/unit/actions/services/service_instance_update_managed_spec.rb
  spec/unit/actions/v3/service_instance_create_managed_spec.rb
  spec/unit/actions/v3/service_instance_update_managed_spec.rb
  spec/unit/jobs/v3/create_service_instance_job_spec.rb
  spec/unit/jobs/v3/delete_service_instance_job_spec.rb
  spec/unit/jobs/v3/service_instance_async_job_spec.rb
  spec/unit/jobs/v3/update_service_instance_job_spec.rb
Labels: in progress

#2117 v3(services): service_plan_visibility performance improvement
  app/models/services/service_plan.rb
Labels: delivered, sapi

#2116 Update dashboard url on service instance async operation completion
  app/actions/v3/service_instance_create_managed.rb
  app/actions/v3/service_instance_update_managed.rb
  spec/request/service_instances_spec.rb
  spec/unit/actions/v3/service_instance_create_managed_spec.rb
  spec/unit/actions/v3/service_instance_update_managed_spec.rb
Labels: scheduled

#2118 Added telemetry when binding to app is requested
  app/controllers/v3/service_credential_bindings_controller.rb
  spec/request/service_credential_bindings_spec.rb
Labels: scheduled

#2119 v3: Support binding name in app manifest
  app/actions/app_apply_manifest.rb
  app/messages/manifest_service_binding_create_message.rb
  spec/request/space_manifests_spec.rb
  spec/unit/actions/app_apply_manifest_spec.rb
  spec/unit/messages/manifest_service_binding_create_message_spec.rb
Labels: scheduled

#2095 v3(services) Remove experimental service_binding resourece.
  app/actions/v2/services/service_binding_create.rb
  app/actions/v2/services/service_binding_delete.rb
  app/actions/v2/services/service_binding_read.rb
  app/controllers/services/lifecycle/service_instance_purger.rb
  app/controllers/services/service_bindings_controller.rb
  app/controllers/v3/service_bindings_controller.rb
  app/fetchers/service_binding_list_fetcher.rb
  app/messages/service_bindings_list_message.rb
  app/presenters/v3/service_binding_presenter.rb
  docs/v3/source/includes/api_resources/_service_bindings.erb
  docs/v3/source/includes/experimental_resources/service_bindings/_create.md.erb
  docs/v3/source/includes/experimental_resources/service_bindings/_delete.md
  docs/v3/source/includes/experimental_resources/service_bindings/_get.md.erb
  docs/v3/source/includes/experimental_resources/service_bindings/_header.md
  docs/v3/source/includes/experimental_resources/service_bindings/_list.md.erb
  docs/v3/source/includes/experimental_resources/service_bindings/_object.md.erb
  docs/v3/source/index.html.md
  spec/request/service_bindings_spec.rb
  spec/unit/actions/v2/services/service_binding_create_spec.rb
  spec/unit/actions/v2/services/service_binding_delete_spec.rb
  spec/unit/actions/v2/services/service_binding_read_spec.rb
  spec/unit/controllers/v3/service_bindings_controller_spec.rb
  spec/unit/fetchers/service_binding_list_fetcher_spec.rb
  spec/unit/messages/service_bindings_list_message_spec.rb
  spec/unit/presenters/v3/service_binding_presenter_spec.rb
Labels: delivered

#2125 v3(services): perf: many orgs slows POST /v3/service_plan/:guid/visib…
  app/actions/v3/service_plan_visibility_update.rb
  app/controllers/v3/service_plan_visibility_controller.rb
  app/presenters/v3/service_plan_visibility_presenter.rb
  docs/v3/source/includes/api_resources/_service_plan_visibility.erb
  docs/v3/source/includes/resources/service_plan_visibility/_apply.md.erb
  spec/request/service_plan_visibility_spec.rb
  spec/unit/presenters/v3/service_plan_visibility_presenter_spec.rb
Labels: scheduled

#2127 Update param response for UPSI to 400 with error
  app/controllers/v3/service_instances_controller.rb
  docs/v3/source/includes/resources/service_instances/_parameters.md.erb
  spec/request/service_instances_spec.rb
Labels: delivered

#2123 Re-introduce prevention of unnecessary retrying of fetching stats for stopped OPI instances
  lib/cloud_controller/opi/instances_client.rb
  spec/unit/lib/cloud_controller/opi/instances_client_spec.rb
Labels: unscheduled

#2131 services: allow longer service instance names
  app/models/services/service_instance.rb
  spec/unit/controllers/services/service_instances_controller_spec.rb
  spec/unit/controllers/services/user_provided_service_instances_controller_spec.rb
  spec/unit/models/services/service_instance_spec.rb
Labels: in progress

#2079 ISSUE-2040-favor-401-over-429
  middleware/security_context_setter.rb
  spec/unit/middleware/security_context_setter_spec.rb
Labels: unscheduled
