Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-03, with the labels that each got.

#2087 Absolute metric for outstanding requests
  lib/cloud_controller/metrics/request_metrics.rb
  spec/unit/lib/cloud_controller/metrics/request_metrics_spec.rb
Labels: unscheduled

#2138 Make nginx timeout configurable
  lib/cloud_controller/drain.rb
  spec/unit/lib/cloud_controller/drain_spec.rb
Labels: unscheduled

#2133 Fix buildpack delete race condition
  app/actions/buildpack_delete.rb
  spec/unit/actions/buildpack_delete_spec.rb
Labels: unscheduled

#2053 Validate JobPollableModel is updated before DelayedJob
  spec/unit/jobs/enqueuer_async_spec.rb
Labels: enhancement, unscheduled

#2148 Log and save compound errors with V3ErrorHasher in LoggingContextJob
  app/jobs/logging_context_job.rb
  spec/unit/jobs/logging_context_job_spec.rb
Labels: unscheduled

#2153 Added SI related info for orphan mitigation
  decisions/0009-services-bindings-orphan-mitigation.md
Labels: scheduled

#2154 Sending app annotation to service broker on bind request
  app/models/services/route_binding.rb
  app/models/services/service_binding.rb
  app/models/services/service_key.rb
  lib/services/service_brokers/v2/client.rb
  spec/request/service_credential_bindings_spec.rb
  spec/support/shared_examples/request/bindings_create.rb
  spec/unit/controllers/services/service_bindings_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
  spec/unit/models/services/service_binding_spec.rb
Labels: delivered

#2156 Send annotation to broker in context
  docs/v3/source/includes/concepts/_metadata.md.erb
  lib/services/service_brokers/v2/client.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_instances_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/request/bindings_create.rb
  spec/unit/controllers/services/service_bindings_controller_spec.rb
  spec/unit/controllers/services/service_keys_controller_spec.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: delivered

#2158 Send only public annotations
  docs/v3/source/includes/concepts/_metadata.md.erb
  lib/services/service_brokers/v2/client.rb
  spec/request/service_credential_bindings_spec.rb
  spec/request/service_instances_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/shared_examples/request/bindings_create.rb
  spec/unit/lib/services/service_brokers/v2/client_spec.rb
Labels: unscheduled

#2150 Enhance nginx drain script
  lib/cloud_controller/drain.rb
  spec/unit/lib/cloud_controller/drain_spec.rb
Labels: unscheduled

#2165 Minor wording fixes to documentation of annotations sent to brokers
  docs/v3/source/includes/concepts/_metadata.md.erb
Labels: unscheduled

#2155 Add basic Zipkin instrumentation
  lib/cloud_controller/rack_app_builder.rb
  lib/services/service_brokers/v2/http_client.rb
  lib/vcap/request.rb
  middleware/zipkin.rb
  spec/unit/lib/vcap/request_spec.rb
  spec/unit/middleware/zipkin_spec.rb
Labels: in progress
