Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-05, with the labels that each got.

#2257 Fix typo in service_credential_bindings docs
  docs/v3/source/includes/resources/service_credential_bindings/_details.md.erb
  docs/v3/source/includes/resources/service_credential_bindings/_get.md.erb
Labels: unscheduled

#2258 Do not set VCAP_APPLICATION env var during kpack staging
  lib/cloud_controller/kpack/stager.rb
  spec/unit/lib/cloud_controller/kpack/stager_spec.rb
Labels: unscheduled

#2255 Speed up v3 security groups
  app/presenters/v3/security_group_presenter.rb
Labels: unscheduled

#2251 Space application supporter role
  app/actions/role_create.rb
  app/actions/role_delete.rb
  app/messages/role_create_message.rb
  app/models.rb
  app/models/helpers/role_types.rb
  app/models/runtime/helpers/organization_role_mixin.rb
  app/models/runtime/helpers/space_role_mixin.rb
  app/models/runtime/organization_auditor.rb
  app/models/runtime/organization_billing_manager.rb
  app/models/runtime/organization_manager.rb
  app/models/runtime/organization_user.rb
  app/models/runtime/role.rb
  app/models/runtime/space.rb
  app/models/runtime/space_application_supporter.rb
  app/models/runtime/space_auditor.rb
  app/models/runtime/space_developer.rb
  app/models/runtime/space_manager.rb
  app/models/runtime/user.rb
  db/migrations/20210427221541_create_spaces_application_supporters_table.rb
  docs/v3/package-lock.json
  docs/v3/source/includes/resources/roles/_valid_roles.md.erb
  lib/cloud_controller/config_schemas/base/api_schema.rb
  lib/cloud_controller/membership.rb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/apps_spec.rb
  spec/request/service_route_bindings_spec.rb
  spec/support/fakes/blueprints.rb
  spec/support/user_header_helpers.rb
  spec/support/user_helpers.rb
  spec/unit/actions/role_create_spec.rb
  spec/unit/actions/role_delete_spec.rb
  spec/unit/actions/user_delete_spec.rb
  spec/unit/lib/cloud_controller/membership_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
  spec/unit/messages/role_create_message_spec.rb
  spec/unit/models/runtime/role_spec.rb
  spec/unit/models/runtime/space_application_supporter_spec.rb
  spec/unit/models/runtime/user_spec.rb
Labels: space-application-supporter, unscheduled

#2260 Space application supporter roles permissions
  app/models/runtime/space.rb
  docs/v3/source/includes/resources/roles/_get.md.erb
  spec/request/roles_spec.rb
Labels: space-application-supporter

#2256 Log incomplete requests when stopping CC
  lib/cloud_controller/logs/request_logs.rb
  lib/cloud_controller/rack_app_builder.rb
  lib/cloud_controller/runner.rb
  middleware/request_logs.rb
  spec/spec_helper.rb
  spec/support/request_spec_helper.rb
  spec/unit/lib/cloud_controller/logs/request_logs_spec.rb
  spec/unit/lib/cloud_controller/rack_app_builder_spec.rb
  spec/unit/lib/cloud_controller/runner_spec.rb
  spec/unit/middleware/request_logs_spec.rb
  spec/unit/middleware/request_metrics_spec.rb
Labels: scheduled

#2282 Space application supporter apps permissions
  app/controllers/v3/apps_controller.rb
  app/controllers/v3/builds_controller.rb
  lib/cloud_controller/membership.rb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/apps_spec.rb
  spec/unit/actions/user_delete_spec.rb
  spec/unit/controllers/v3/apps_controller_spec.rb
  spec/unit/models/runtime/user_spec.rb
Labels: unscheduled

#2293 Log service broker requests at info level
  lib/services/service_brokers/v2/http_client.rb
  spec/unit/lib/services/service_brokers/v2/http_client_spec.rb
Labels: unscheduled

#2288 Allow application supporters to use route endpoints
  app/controllers/v3/domains_controller.rb
  app/controllers/v3/routes_controller.rb
  app/controllers/v3/spaces_controller.rb
  app/models/runtime/app_model.rb
  app/models/runtime/route.rb
  app/models/runtime/space.rb
  docs/v3/source/includes/resources/routes/_check_route_reservations.md.erb
  docs/v3/source/includes/resources/routes/_create.md.erb
  docs/v3/source/includes/resources/routes/_delete.md.erb
  docs/v3/source/includes/resources/routes/_delete_unmapped.md.erb
  docs/v3/source/includes/resources/routes/_get.md.erb
  docs/v3/source/includes/resources/routes/_insert_destinations.md.erb
  docs/v3/source/includes/resources/routes/_list_destinations.md.erb
  docs/v3/source/includes/resources/routes/_list_for_app.md.erb
  docs/v3/source/includes/resources/routes/_remove_destination.md.erb
  docs/v3/source/includes/resources/routes/_replace_destinations.md.erb
  docs/v3/source/includes/resources/routes/_update.md.erb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  spec/request/domains_spec.rb
  spec/request/route_destinations_spec.rb
  spec/request/routes_spec.rb
  spec/request/spaces_spec.rb
  spec/support/user_helpers.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
  spec/unit/models/runtime/space_spec.rb
Labels: unscheduled
