Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2021-07, with the labels that each got.

#2350 Space application supporter revisions
  app/controllers/v3/app_revisions_controller.rb
  app/controllers/v3/revisions_controller.rb
  docs/v3/source/includes/experimental_resources/revisions/_deployed_list.md.erb
  docs/v3/source/includes/experimental_resources/revisions/_get.md.erb
  docs/v3/source/includes/experimental_resources/revisions/_list.md.erb
  spec/request/revisions_spec.rb
Labels: space-application-supporter, unscheduled

#2359 Space supporter process write permissions
  app/controllers/v3/processes_controller.rb
  docs/v3/source/includes/resources/processes/_get.md.erb
  docs/v3/source/includes/resources/processes/_list_for_app.md.erb
  docs/v3/source/includes/resources/processes/_scale.md.erb
  docs/v3/source/includes/resources/processes/_stats.md.erb
  docs/v3/source/includes/resources/processes/_terminate_instance.md
  docs/v3/source/includes/resources/processes/_update.md.erb
  spec/request/processes_spec.rb
  spec/request_spec_shared_examples.rb
  spec/unit/controllers/v3/processes_controller_spec.rb
Labels: space-application-supporter, unscheduled

#2346 Space application supporter can get and list space quotas
  app/controllers/v3/space_quotas_controller.rb
  app/models/runtime/space_quota_definition.rb
  docs/v3/source/includes/resources/space_quotas/_get.md.erb
  spec/request/space_quotas_spec.rb
Labels: space-application-supporter, unscheduled

#2323 Space application supporter can access deployments endpoints
  app/controllers/v3/deployments_controller.rb
  docs/v3/source/includes/resources/deployments/_cancel.md.erb
  docs/v3/source/includes/resources/deployments/_create.md.erb
  docs/v3/source/includes/resources/deployments/_get.md.erb
  docs/v3/source/includes/resources/deployments/_list.md.erb
  docs/v3/source/includes/resources/deployments/_update.md.erb
  spec/request/deployments_spec.rb
Labels: space-application-supporter

#2343 Allow space application supporter to access specific sidecar endpoints
  app/controllers/v3/sidecars_controller.rb
  docs/v3/source/includes/experimental_resources/sidecars/_get.md.erb
  docs/v3/source/includes/experimental_resources/sidecars/_list_for_app.md.erb
  docs/v3/source/includes/experimental_resources/sidecars/_list_for_process.md.erb
  spec/request/sidecars_spec.rb
Labels: space-application-supporter, unscheduled

#2390 Allow space application supporter to access specific build endpoints.
  Gemfile.lock
  app/controllers/v3/builds_controller.rb
  docs/v3/source/includes/resources/builds/_create.md.erb
  docs/v3/source/includes/resources/builds/_get.md.erb
  spec/request/apps_spec.rb
  spec/request/builds_spec.rb
Labels: space-application-supporter, unscheduled

#2396 SAP contribution: fix unsafe navigation from non existing space to org
  lib/cloud_controller/permissions.rb
Labels: unscheduled

#2407 Return 403 for Space Support on PATCH /v3/builds/:guid
  app/controllers/v3/builds_controller.rb
  spec/request/builds_spec.rb
Labels: space-application-supporter, unscheduled

#2405 Removing perm
  .travis.yml
  Gemfile
  Gemfile.lock
  app/actions/organization_create.rb
  app/actions/space_create.rb
  app/controllers/base/base_controller.rb
  app/controllers/v3/application_controller.rb
  app/controllers/v3/spaces_controller.rb
  app/controllers/v3/tasks_controller.rb
  config/cloud_controller.yml
  lib/cloud_controller.rb
  lib/cloud_controller/config_schemas/base/api_schema.rb
  lib/cloud_controller/controller_factory.rb
  lib/cloud_controller/dependency_locator.rb
  lib/cloud_controller/perm/client.rb
  lib/cloud_controller/perm/errors.rb
  lib/cloud_controller/perm/permissions.rb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/permissions/queryer.rb
  lib/cloud_controller/science/experiment.rb
  spec/fixtures/config/port_8181_config.yml
  spec/integration/v2_perm_spec.rb
  spec/integration/v3_perm_spec.rb
  spec/spec_helper.rb
  spec/support/user_helpers.rb
  spec/unit/access/organization_access_spec.rb
  spec/unit/access/route_access_spec.rb
  spec/unit/access/space_access_spec.rb
  spec/unit/actions/droplet_delete_spec.rb
  spec/unit/actions/space_create_spec.rb
  spec/unit/controllers/base/base_controller_spec.rb
  spec/unit/controllers/base/model_controller_spec.rb
  spec/unit/controllers/internal/log_access_controller_spec.rb
  spec/unit/controllers/runtime/legacy_api_base_spec.rb
  spec/unit/controllers/services/service_keys_controller_spec.rb
  spec/unit/controllers/v3/app_features_controller_spec.rb
  spec/unit/controllers/v3/application_controller_spec.rb
  spec/unit/controllers/v3/tasks_controller_spec.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
  spec/unit/lib/perm/client_spec.rb
  spec/unit/lib/perm/permissions_spec.rb
  spec/unit/lib/permissions/queryer_spec.rb
Labels: unscheduled

#2341 Space application supporter can get and list security groups
  app/controllers/v3/security_groups_controller.rb
  app/controllers/v3/spaces_controller.rb
  app/models/runtime/security_group.rb
  docs/v3/source/includes/experimental_resources/sidecars/_get.md.erb
  docs/v3/source/includes/experimental_resources/sidecars/_list_for_app.md.erb
  docs/v3/source/includes/experimental_resources/sidecars/_list_for_process.md.erb
  docs/v3/source/includes/resources/security_groups/_get.md.erb
  docs/v3/source/includes/resources/security_groups/_list.md.erb
  docs/v3/source/includes/resources/security_groups/_list_running_security_groups.md.erb
  docs/v3/source/includes/resources/security_groups/_list_staging_security_groups.md.erb
  spec/request/processes_spec.rb
  spec/request/security_groups_spec.rb
  spec/request/spaces_spec.rb
Labels: space-application-supporter, unscheduled

#2395 Space supporter can access correct org quotas endpoints
  docs/v3/source/includes/resources/organization_quotas/_get.md.erb
  docs/v3/source/includes/resources/organization_quotas/_list.md.erb
  spec/request/organization_quotas_spec.rb
Labels: space-application-supporter, unscheduled

#2351 Support expiring of DB connections
  lib/cloud_controller/config_schemas/base/api_schema.rb
  lib/cloud_controller/db.rb
Labels: scheduled

#2349 Allow space application supporter to access specific service plan endpoints
  app/controllers/v3/mixins/service_permissions.rb
  app/controllers/v3/service_plans_controller.rb
  lib/cloud_controller/permissions.rb
  spec/request/service_plan_visibility_spec.rb
  spec/request/service_plans_spec.rb
Labels: space-application-supporter, unscheduled

#2376 Space application supporter can list and cancel tasks
  app/controllers/v3/tasks_controller.rb
  docs/v3/source/includes/resources/tasks/_cancel.md.erb
  docs/v3/source/includes/resources/tasks/_get.md.erb
  docs/v3/source/includes/resources/tasks/_list_for_app.md.erb
  spec/request/tasks_spec.rb
  spec/request_spec_shared_examples.rb
Labels: space-application-supporter, unscheduled

#2408 Allow space supporter to access specific service broker endpoints
  app/controllers/v3/service_brokers_controller.rb
  docs/v3/source/includes/resources/app_features/_update.md.erb
  docs/v3/source/includes/resources/droplets/_get.md.erb
  docs/v3/source/includes/resources/processes/_get.md.erb
  docs/v3/source/includes/resources/processes/_stats.md.erb
  docs/v3/source/includes/resources/service_brokers/_get.md.erb
  docs/v3/source/includes/resources/service_brokers/_list.md.erb
  docs/v3/source/includes/resources/users/_get.md.erb
  docs/v3/source/includes/resources/users/_list.md.erb
  lib/cloud_controller/permissions.rb
  spec/request/service_brokers_spec.rb
Labels: space-application-supporter, unscheduled

#2414 Space supporter receives a 403 for v3/deployments/:guid
  app/controllers/v3/deployments_controller.rb
  spec/request/deployments_spec.rb
Labels: space-application-supporter, unscheduled

#2412 Ensure space supporter receives error code for specific manifest endpoints
  app/controllers/v3/app_manifests_controller.rb
  app/controllers/v3/space_manifests_controller.rb
  spec/request/app_manifests_spec.rb
  spec/request/space_manifests_spec.rb
Labels: space-application-supporter, unscheduled

#2417 space supporter receives a 403 when accessing PATCH /v3/tasks/:guid
  app/controllers/v3/tasks_controller.rb
  spec/request/tasks_spec.rb
Labels: space-application-supporter

#2369 Space application supporter can get, create and delete service route bindings
  app/controllers/v3/service_route_bindings_controller.rb
  docs/v3/source/includes/resources/service_route_bindings/_create.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_delete.md.erb
  docs/v3/source/includes/resources/service_route_bindings/_get.md.erb
  spec/request/service_route_bindings_spec.rb
Labels: space-application-supporter, unscheduled

#2420 Add connection expiration to deployment_updater_schema
  lib/cloud_controller/config_schemas/base/deployment_updater_schema.rb
  lib/cloud_controller/db.rb
Labels: unscheduled

#2423 Clean up isolation segment specs
  spec/request/isolation_segments_spec.rb
  spec/unit/controllers/v3/isolation_segments_controller_spec.rb
Labels: unscheduled

#2425 Return 403 for space supporter delete and patch app
  app/controllers/v3/apps_controller.rb
  spec/request/apps_spec.rb
  spec/unit/controllers/v3/apps_controller_spec.rb
Labels: space-application-supporter, unscheduled

#2378 Space application supporter can get, list service instances
  app/controllers/v3/service_instances_controller.rb
  docs/v3/source/includes/resources/service_instances/_get.md.erb
  docs/v3/source/includes/resources/service_instances/_list_shared_spaces.md.erb
  spec/request/service_instances_spec.rb
Labels: space-application-supporter, unscheduled

#2415 Adds permissions tests for V3 users
  spec/request/users_spec.rb
Labels: space-application-supporter, unscheduled

#2418 Allow space supporter to access specific organizations endpoints
  spec/request/organizations_spec.rb
  spec/unit/controllers/v3/organizations_controller_spec.rb
Labels: space-application-supporter, unscheduled

#2419 Return 403 for unauthorized packages endpoints for space supporter
  app/controllers/v3/packages_controller.rb
  spec/request/packages_spec.rb
Labels: space-application-supporter, unscheduled

#2424 Ensure Space Supporter receives 403 when trying to update service route binding
  app/controllers/v3/service_route_bindings_controller.rb
  spec/request/service_route_bindings_spec.rb
Labels: space-application-supporter, unscheduled

#2426 Allows space supporter to access GET v3/service_route_bindings
  app/controllers/v3/service_route_bindings_controller.rb
  docs/v3/source/includes/resources/service_route_bindings/_list.md.erb
  spec/request/service_route_bindings_spec.rb
Labels: space-application-supporter, unscheduled

#2427 Clarified the wording of `apps.per_app_tasks`
  docs/v2/organization_quota_definitions/creating_a_organization_quota_definition.html
  docs/v2/organization_quota_definitions/updating_a_organization_quota_definition.html
  docs/v2/space_quota_definitions/creating_a_space_quota_definition.html
  docs/v2/space_quota_definitions/updating_a_space_quota_definition.html
  docs/v3/source/includes/resources/organization_quotas/_create.md.erb
  docs/v3/source/includes/resources/organization_quotas/_object.md.erb
  docs/v3/source/includes/resources/organization_quotas/_update.md.erb
  docs/v3/source/includes/resources/space_quotas/_create.md.erb
  docs/v3/source/includes/resources/space_quotas/_object.md.erb
  docs/v3/source/includes/resources/space_quotas/_update.md.erb
Labels: api-docs, unscheduled

#2394 ISSUE-2393 Catch exceptions and decrease outstanding requests metric
  middleware/request_metrics.rb
  spec/unit/middleware/request_metrics_spec.rb
Labels: unscheduled

#2364 Space application supporter can list service offerings
  app/controllers/v3/service_offerings_controller.rb
  spec/request/service_offerings_spec.rb
Labels: space-application-supporter, unscheduled

#2388 Space supporter can get and update app environment variables
  app/controllers/v3/apps_controller.rb
  app/presenters/v3/app_env_presenter.rb
  docs/v2/feature_flags/get_the_space_developer_environment_variable_visibility_feature_flag_(experimental).html
  docs/v3/source/includes/resources/apps/_env.md.erb
  docs/v3/source/includes/resources/apps/_environment_variables.md.erb
  docs/v3/source/includes/resources/apps/_update_environment_variables.md.erb
  docs/v3/source/includes/resources/feature_flags/_flags.md.erb
  lib/cloud_controller/permissions.rb
  spec/api/documentation/feature_flags_api_spec.rb
  spec/request/apps_spec.rb
  spec/support/user_helpers.rb
  spec/unit/presenters/v3/app_env_presenter_spec.rb
Labels: space-application-supporter, unscheduled

#2438 A service instance can no longer shared if a service instance's name is already in use in the target space.
  app/actions/service_instance_share.rb
  spec/unit/actions/service_instance_share_spec.rb
Labels: bug

#2431 Allow space supporter to get ssh_enabled app feature and to access apps in the stack
  app/controllers/v3/app_features_controller.rb
  app/controllers/v3/stacks_controller.rb
  docs/v3/source/includes/resources/apps/_ssh_enabled.md.erb
  docs/v3/source/includes/resources/stacks/_apps.md.erb
  docs/v3/source/index.html.md
  spec/request/apps_spec.rb
  spec/request/stacks_spec.rb
Labels: space-application-supporter, unscheduled

#2370 Truncate large process crash events
  app/repositories/app_event_repository.rb
  app/repositories/mixins/truncation_mixin.rb
  app/repositories/process_event_repository.rb
  spec/unit/repositories/process_event_repository_spec.rb
Labels: unscheduled

#2440 Allow user to filter routes by service instance guid
  app/fetchers/route_fetcher.rb
  app/messages/routes_list_message.rb
  docs/v3/source/includes/resources/routes/_list.md.erb
  spec/request/routes_spec.rb
  spec/unit/fetchers/route_fetcher_spec.rb
Labels: unscheduled

#2446 Create new table to store newly created space_supporters in an appropriately named table
  app/models/runtime/app_model.rb
  app/models/runtime/route.rb
  app/models/runtime/security_group.rb
  app/models/runtime/space.rb
  app/models/runtime/space_quota_definition.rb
  app/models/runtime/space_supporter.rb
  app/models/runtime/user.rb
  db/migrations/20210708215223_create_spaces_supporters_table.rb
  decisions/0010-renaming-space-application-suporter-role-to-space-supporter.md
  lib/cloud_controller/membership.rb
  spec/unit/models/runtime/space_spec.rb
  spec/unit/models/runtime/space_supporter_spec.rb
  spec/unit/models/runtime/user_spec.rb
Labels: space-application-supporter, unscheduled

#2428 Space supporter unauthorized droplet endpoints
  app/controllers/v3/droplets_controller.rb
  docs/v3/source/includes/resources/droplets/_update.md.erb
  spec/request/droplets_spec.rb
Labels: space-application-supporter, unscheduled

#2353 Replace readable_org_guids_for_domains with query
  app/controllers/v3/organizations_controller.rb
  lib/cloud_controller/membership.rb
  lib/cloud_controller/permissions.rb
  spec/unit/fetchers/domain_fetcher_spec.rb
  spec/unit/lib/cloud_controller/membership_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: scheduled
