Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2022-10, with the labels that each got.

#2997 Reduce db queries for /organizations/:guid/domains
  app/controllers/v3/organizations_controller.rb
Labels: unscheduled

#2967 Remove redundant locks and transactions
  app/actions/services/locks/deleter_lock.rb
  app/actions/services/locks/updater_lock.rb
  app/actions/v3/service_instance_create_managed.rb
  app/actions/v3/service_instance_update_managed.rb
Labels: unscheduled

#2971 Optimisations for /v3/roles API calls
  app/controllers/v3/roles_controller.rb
  app/decorators/include_role_organization_decorator.rb
  app/models/runtime/role.rb
  spec/request/roles_spec.rb
  spec/unit/decorators/include_role_organization_decorator_spec.rb
Labels: unscheduled

#3010 Increase the webdav receive_timeout to 120 seconds
  lib/cloud_controller/blobstore/webdav/dav_client.rb
  lib/cloud_controller/blobstore/webdav/http_client_provider.rb
Labels: unscheduled

#3009 Raise an exception if user can read globally
  lib/cloud_controller/permissions.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: unscheduled

#3003 Attempt to refactor service_instance_list_fetcher perm logic
  app/controllers/v3/service_instances_controller.rb
  app/fetchers/service_instance_list_fetcher.rb
  spec/unit/fetchers/service_instance_list_fetcher_spec.rb
Labels: unscheduled

#2929 Add an unique index to service_instance_operations
  db/migrations/20220818142407_add_unique_index_to_service_instance_operations_service_instance_id.rb
  spec/migrations/20220818142407_add_unique_index_to_service_instance_operations_service_instance_id_spec.rb
  spec/unit/models/services/service_instance_operation_spec.rb
Labels: unscheduled, needs_review

#3006 Remove bits-service leftovers
  Gemfile
  Gemfile.lock
  app/controllers/runtime/info_controller.rb
  app/controllers/runtime/resource_matches_controller.rb
  app/controllers/runtime/root_controller.rb
  app/controllers/v3/packages_controller.rb
  app/controllers/v3/resource_matches_controller.rb
  app/presenters/v3/package_presenter.rb
  config/bosh-lite.yml
  config/cloud_controller.yml
  docs/v3/source/includes/api_resources/_root.erb
  errors/v2.yml
  lib/cloud_controller/bits_service_resource_pool_wrapper.rb
  lib/cloud_controller/blobstore/client_provider.rb
  lib/cloud_controller/config_schemas/base/api_schema.rb
  lib/cloud_controller/config_schemas/base/clock_schema.rb
  lib/cloud_controller/config_schemas/base/deployment_updater_schema.rb
  lib/cloud_controller/config_schemas/base/worker_schema.rb
  lib/cloud_controller/dependency_locator.rb
  lib/cloud_controller/packager/bits_service_packer.rb
  scripts/cf-release/restore-bosh-lite-cc.sh
  scripts/cf-release/setup-local-cc.sh
  scripts/short-circuit-cc
  spec/fixtures/config/port_8181_config.yml
  spec/request/vcap_request_id_resource_pool_spec.rb
  spec/unit/controllers/runtime/info_controller_spec.rb
  spec/unit/controllers/runtime/resource_matches_controller_spec.rb
  spec/unit/controllers/runtime/root_controller_spec.rb
  spec/unit/controllers/v3/packages_controller_spec.rb
  spec/unit/lib/background_job_environment_spec.rb
  spec/unit/lib/cloud_controller/config_spec.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
  spec/unit/lib/cloud_controller/packager/bits_service_packer_spec.rb
  spec/unit/presenters/v3/package_presenter_spec.rb
Labels: unscheduled

#2993 V2 rate limit exclusions
  errors/v2.yml
  lib/cloud_controller/roles.rb
  lib/cloud_controller/security_context.rb
  middleware/rate_limiter_v2_api.rb
  spec/unit/middleware/rate_limiter_v2_api_spec.rb
  spec/unit/middleware/security_context_setter_spec.rb
Labels: unscheduled

#3014 Refactor service_instance_list_fetcher perm logic
  app/controllers/v3/service_instances_controller.rb
  app/fetchers/service_instance_list_fetcher.rb
  spec/unit/fetchers/service_instance_list_fetcher_spec.rb
Labels: unscheduled

#3008 Various sequel improvements
  app/controllers/v3/isolation_segments_controller.rb
  app/controllers/v3/mixins/service_permissions.rb
  app/controllers/v3/organization_quotas_controller.rb
  app/controllers/v3/organizations_controller.rb
  app/fetchers/base_service_list_fetcher.rb
  app/fetchers/isolation_segment_list_fetcher.rb
  app/fetchers/isolation_segment_organizations_fetcher.rb
  app/fetchers/organization_quota_list_fetcher.rb
  app/fetchers/service_plan_visibility_fetcher.rb
  lib/cloud_controller/membership.rb
  lib/cloud_controller/permissions.rb
  spec/request/organizations_spec.rb
  spec/request/service_plan_visibility_spec.rb
  spec/unit/fetchers/isolation_segment_list_fetcher_spec.rb
  spec/unit/fetchers/isolation_segment_organizations_fetcher_spec.rb
  spec/unit/fetchers/organization_quota_list_fetcher_spec.rb
  spec/unit/fetchers/service_plan_visibility_fetcher_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
  spec/unit/models/runtime/route_spec.rb
  spec/unit/models/runtime/user_spec.rb
Labels: unscheduled, needs_review

#3031 Fix two typos in API docs
  docs/v3/source/includes/concepts/_metadata.md.erb
  docs/v3/source/includes/resources/apps/_list.md.erb
Labels: unscheduled, api-docs

#3021 Check space/org permissions by id, not guid
  app/access/organization_access.rb
  app/access/route_access.rb
  app/access/space_access.rb
  app/controllers/runtime/apps_controller.rb
  app/controllers/runtime/route_mappings_controller.rb
  app/controllers/services/service_bindings_controller.rb
  app/controllers/v3/app_features_controller.rb
  app/controllers/v3/app_manifests_controller.rb
  app/controllers/v3/app_revisions_controller.rb
  app/controllers/v3/apps_controller.rb
  app/controllers/v3/builds_controller.rb
  app/controllers/v3/deployments_controller.rb
  app/controllers/v3/domains_controller.rb
  app/controllers/v3/droplets_controller.rb
  app/controllers/v3/organizations_controller.rb
  app/controllers/v3/packages_controller.rb
  app/controllers/v3/processes_controller.rb
  app/controllers/v3/revisions_controller.rb
  app/controllers/v3/roles_controller.rb
  app/controllers/v3/routes_controller.rb
  app/controllers/v3/security_groups_controller.rb
  app/controllers/v3/service_brokers_controller.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/controllers/v3/service_instances_controller.rb
  app/controllers/v3/service_route_bindings_controller.rb
  app/controllers/v3/sidecars_controller.rb
  app/controllers/v3/space_features_controller.rb
  app/controllers/v3/space_manifests_controller.rb
  app/controllers/v3/space_quotas_controller.rb
  app/controllers/v3/spaces_controller.rb
  app/controllers/v3/tasks_controller.rb
  app/fetchers/add_route_fetcher.rb
  app/fetchers/app_fetcher.rb
  app/fetchers/assign_current_droplet_fetcher.rb
  app/fetchers/droplet_fetcher.rb
  app/fetchers/package_fetcher.rb
  app/fetchers/process_fetcher.rb
  app/fetchers/sidecar_list_fetcher.rb
  app/fetchers/task_create_fetcher.rb
  app/fetchers/task_fetcher.rb
  app/models/services/service_key.rb
  lib/app_log_emitter.rb
  lib/cloud_controller/membership.rb
  lib/cloud_controller/permissions.rb
  spec/support/user_helpers.rb
  spec/unit/actions/space_delete_spec.rb
  spec/unit/fetchers/add_route_fetcher_spec.rb
  spec/unit/fetchers/app_fetcher_spec.rb
  spec/unit/fetchers/assign_current_droplet_fetcher_spec.rb
  spec/unit/fetchers/droplet_fetcher_spec.rb
  spec/unit/fetchers/package_fetcher_spec.rb
  spec/unit/fetchers/process_fetcher_spec.rb
  spec/unit/fetchers/task_create_fetcher_spec.rb
  spec/unit/fetchers/task_fetcher_spec.rb
  spec/unit/lib/cloud_controller/membership_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: unscheduled

#3039 Fix v3 upgrade guide for audit_events
  docs/v3/source/includes/upgrade_guide/changed_resources/_audit_events_in_v3.md
Labels: unscheduled

#3033 Use foreign keys more to avoid DB queries
  app/access/route_access.rb
  app/actions/droplet_create.rb
  app/actions/manifest_route_update.rb
  app/actions/service_credential_binding_app_create.rb
  app/actions/sidecar_synchronize_from_app_droplet.rb
  app/actions/sidecar_update.rb
  app/actions/v2/route_mapping_create.rb
  app/controllers/runtime/app_bits_upload_controller.rb
  app/controllers/runtime/apps_controller.rb
  app/controllers/runtime/restages_controller.rb
  app/controllers/v3/builds_controller.rb
  app/controllers/v3/processes_controller.rb
  app/controllers/v3/routes_controller.rb
  app/controllers/v3/service_credential_bindings_controller.rb
  app/fetchers/droplet_list_fetcher.rb
  app/models/runtime/space.rb
  app/models/services/service_plan.rb
  app/presenters/v3/build_presenter.rb
  app/presenters/v3/deployment_presenter.rb
  app/presenters/v3/revision_environment_variables_presenter.rb
  app/presenters/v3/shared_spaces_usage_summary_presenter.rb
  app/presenters/v3/task_presenter.rb
  app/repositories/app_usage_event_repository.rb
  app/repositories/build_event_repository.rb
  app/repositories/droplet_event_repository.rb
  app/repositories/package_event_repository.rb
  app/repositories/process_event_repository.rb
  app/repositories/route_event_repository.rb
  app/repositories/task_event_repository.rb
  lib/cloud_controller/deployments/deployment_target_state.rb
  lib/cloud_controller/diego/app_recipe_builder.rb
  lib/cloud_controller/diego/buildpack/lifecycle_protocol.rb
  lib/cloud_controller/diego/protocol/container_network_info.rb
  lib/cloud_controller/diego/reporters/instances_stats_reporter.rb
  lib/cloud_controller/diego/task_recipe_builder.rb
  lib/cloud_controller/kpack/stager.rb
  lib/cloud_controller/opi/apps_client.rb
  lib/cloud_controller/opi/apps_rest_client.rb
  lib/cloud_controller/opi/stager_client.rb
  lib/cloud_controller/opi/task_client.rb
  lib/cloud_controller/permissions.rb
  lib/services/service_brokers/v2/client.rb
  spec/unit/lib/cloud_controller/opi/task_client_spec.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: unscheduled

#3038 Clean up unused/unnecessary permissions methods
  app/controllers/v3/service_brokers_controller.rb
  lib/cloud_controller/permissions.rb
  spec/unit/lib/cloud_controller/permissions_spec.rb
Labels: unscheduled

#3034 Enable CC to process large manifests
  app/controllers/v3/application_controller.rb
  spec/request/space_manifests_spec.rb
Labels: unscheduled

#3040 Allow dependabot to update github actions
  .github/dependabot.yml
Labels: unscheduled
