Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2023-10, with the labels that each got.

#3459 Fix ambiguous column in AppListFetcher
  app/fetchers/app_list_fetcher.rb
  spec/request/apps_spec.rb
Labels: unscheduled, needs_review

#3455 Un-pluck Rubocop changes
  app/collection_transformers/usernames_and_roles_populator.rb
  app/fetchers/app_list_fetcher.rb
  lib/cloud_controller/permissions.rb
  lib/cloud_controller/validate_database_keys.rb
Labels: unscheduled

#3464 Do some housekeeping
  app/controllers/v3/service_credential_bindings_controller.rb
  app/jobs/v2/services/legacy_jobs/service_instance_deletion.rb
  docs/v3/source/includes/resources/stacks/_list.md.erb
  lib/cloud_controller/jobs.rb
  spec/unit/lib/cloud_controller/metrics/request_metrics_spec.rb
Labels: needs_review

#3443 Don't show service route binding parameters not in state create succeeded
  app/controllers/v3/service_route_bindings_controller.rb
  spec/request/service_route_bindings_spec.rb
Labels: unscheduled

#3475 Exclude the newly added Readme.md file when checking applied migrations
  lib/tasks/db.rake
Labels: needs_review

#3476 Run the ensure_migrations_are_current rake task in a spec
  spec/migrations/ensure_migrations_are_current_spec.rb
Labels: needs_review

#3470 Use consistent hash structure for process stats
  app/presenters/v3/process_stats_presenter.rb
  lib/cloud_controller/diego/reporters/instances_reporter.rb
  lib/cloud_controller/diego/reporters/instances_stats_reporter.rb
  lib/cloud_controller/diego/reporters/reporter_mixins.rb
  spec/unit/lib/cloud_controller/diego/reporters/instances_stats_reporter_spec.rb
  spec/unit/presenters/v3/process_stats_presenter_spec.rb
Labels: needs_review

#3489 Correct list of buildpack states in docs
  docs/v3/source/includes/resources/buildpacks/_object.md.erb
Labels: needs_review
