Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2023-09, with the labels that each got.

#3423 Run loops in migrations in own transactions
  db/migrations/20230822153000_streamline_annotation_key_prefix.rb
  db/migrations/20230822173000_add_migration_views_for_annotations.rb
Labels: unscheduled

#3417 Make restructure_index migration idempotent and small transactions
  db/migrations/20230725110800_restructure_index_for_improved_pagination_order.rb
Labels: unscheduled

#2881 Codespaces
  .devcontainer/configs/intellij/.idea/inspectionProfiles/Default_CC_NG.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/Rubocop.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Mariadb__CC-Unittests.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Mariadb__CC.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Mariadb__CC_Local_Worker.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Mariadb__CC_Worker.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Postgres__CC-Unittests.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Postgres__CC.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Postgres__CC_Local_Worker.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_Postgres__CC_Worker.xml
  .devcontainer/configs/intellij/.idea/runConfigurations/_template__of_RSpec.xml
  .devcontainer/configs/vscode/.vscode/launch.json
  .devcontainer/configs/vscode/.vscode/settings.json
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.override.yml
  .devcontainer/images/catsbroker/Dockerfile
  .devcontainer/images/devcontainer/Dockerfile
  .devcontainer/images/devcontainer/setup.sh
  .devcontainer/images/nginx/Dockerfile
  .devcontainer/images/nginx/conf/mime.types
  .devcontainer/images/nginx/conf/nginx.conf
  .devcontainer/images/nginx/conf/nginx_external_endpoints.conf
  .devcontainer/images/nginx/conf/public_upload.conf
  .devcontainer/images/uaa/Dockerfile
  .devcontainer/images/uaa/PatchAdminOAuthClient.java
  .devcontainer/scripts/codespaces_init.sh
  .devcontainer/scripts/codespaces_start.sh
  .devcontainer/scripts/setupDevelopmentEnvironment.sh
  .devcontainer/scripts/setupIDEs.sh
  .github/workflows/composite/setup/action.yml
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  devenv.sh
  docker-compose.yml
Labels: delivered

#3421 Bump puma version to resolve cve
  Gemfile.lock
Labels: unscheduled

#3422 Bump grpc to resolve cve
  Gemfile.lock
Labels: unscheduled

#3424 Fix migration deadlock on busy systems
  db/migrations/20230725110800_restructure_index_for_improved_pagination_order.rb
Labels: unscheduled

#3429 Bump activesupport to 6.1.7.6
  Gemfile
  Gemfile.lock
Labels: unscheduled

#3428 Disable automatic transactions, follow up of #3424
  db/migrations/20230725110800_restructure_index_for_improved_pagination_order.rb
  db/migrations/20230822153000_streamline_annotation_key_prefix.rb
  db/migrations/20230822173000_add_migration_views_for_annotations.rb
Labels: unscheduled

#3432 Prevent deletion of service keys by space supporters
  app/controllers/v3/service_credential_bindings_controller.rb
  docs/v3/source/includes/resources/service_credential_bindings/_delete.md.erb
  spec/request/service_credential_bindings_spec.rb
Labels: unscheduled, needs_review

#3439 Remove dedicated org and space role classes
  app/models.rb
  app/models/runtime/organization.rb
  app/models/runtime/organization_role.rb
  app/models/runtime/space.rb
  app/models/runtime/space_role.rb
  spec/unit/models/runtime/organization_role_spec.rb
  spec/unit/models/runtime/space_role_spec.rb
Labels: unscheduled, needs_review

#3414 Add validation for resource match mode
  app/messages/resource_match_create_message.rb
  spec/unit/messages/resource_match_create_message_spec.rb
Labels: unscheduled, needs_review

#3447 kpack_lifecycle_data_model_spec.rb was in the wrong folder, moving it to spec/...
  spec/unit/models/runtime/kpack_lifecycle_data_model_spec.rb
Labels: unscheduled

#3378 Display instance internal IP address on Process Stats endpoint
  app/presenters/v3/process_stats_presenter.rb
  docs/v3/source/includes/api_resources/_processes.erb
  docs/v3/source/includes/resources/processes/_stats_object.md.erb
  spec/request/processes_spec.rb
  spec/unit/presenters/v3/process_stats_presenter_spec.rb
Labels: unscheduled
