Repository cloudfoundry/cloud_controller_ng, pull requests merged in 2023-07, with the labels that each got.

#3324 Fix performance issues with delayed_jobs by extending index
  db/migrations/20230627110500_add_priority_by_to_delayed_jobs_index.rb
Labels: unscheduled

#3290 Use Redis for rate limiters
  Gemfile
  Gemfile.lock
  lib/cloud_controller/config_schemas/base/api_schema.rb
  middleware/base_rate_limiter.rb
  middleware/service_broker_rate_limiter.rb
  spec/spec_helper.rb
  spec/unit/middleware/rate_limiter_spec.rb
  spec/unit/middleware/service_broker_rate_limiter_spec.rb
Labels: unscheduled, needs_review

#3316 Clarify that process stats returns one stats object per instance
  docs/v3/source/includes/api_resources/_processes.erb
  docs/v3/source/includes/resources/processes/_stats.md.erb
  docs/v3/source/includes/resources/processes/_stats_object.md.erb
Labels: unscheduled

#3336 Add linter for syntax errors in the v3 docs examples
  docs/v3/gulpfile.js
  docs/v3/source/includes/concepts/_includes.md.erb
  docs/v3/source/includes/resources/routes/_update_destination.md.erb
Labels: unscheduled

#3326 Add helper script to benchmark rate limiting
  scripts/benchmark_rate_limiting.rb
Labels: unscheduled

#3354 Readiness health checks story 1: adding properties to app manifest
  Gemfile
  Gemfile.lock
  app/messages/app_manifest_message.rb
  app/messages/manifest_process_update_message.rb
  app/messages/process_update_message.rb
  app/messages/validators.rb
  db/migrations/20130730000217_create_service_brokers_table.rb
  spec/request/spaces_spec.rb
  spec/unit/messages/app_manifest_message_spec.rb
  spec/unit/messages/manifest_process_update_message_spec.rb
  spec/unit/messages/process_update_message_spec.rb
Labels: unscheduled

#3350 Remove v3/docs from dependabot config
  .github/dependabot.yml
Labels: unscheduled

#3358 Add delayed_jobs_reserve_where index
  db/migrations/20230726132200_add_delayed_jobs_reserve_where_index.rb
Labels: unscheduled, needs_review

#3353 Limit max pagination depth
  app/controllers/services/service_instances_controller.rb
  app/messages/list_message.rb
  lib/cloud_controller/config_schemas/base/api_schema.rb
  lib/cloud_controller/dependency_locator.rb
  lib/cloud_controller/rest_controller/paginated_collection_renderer.rb
  spec/unit/lib/cloud_controller/dependency_locator_spec.rb
  spec/unit/lib/rest_controller/paginated_collection_renderer_spec.rb
  spec/unit/messages/list_message_spec.rb
Labels: performance

#3346 More aggressive cleanup of failed delayed jobs
  app/jobs/runtime/failed_jobs_cleanup.rb
  app/jobs/runtime/pending_build_cleanup.rb
  app/jobs/runtime/pending_droplet_cleanup.rb
  config/bosh-lite.yml
  config/cloud_controller.yml
  lib/cloud_controller/clock/scheduler.rb
  lib/cloud_controller/config_schemas/base/clock_schema.rb
  spec/fixtures/config/port_8181_config.yml
  spec/unit/jobs/runtime/failed_jobs_cleanup_spec.rb
  spec/unit/jobs/runtime/pending_build_cleanup_spec.rb
  spec/unit/jobs/runtime/pending_droplet_cleanup_spec.rb
  spec/unit/lib/cloud_controller/clock/scheduler_spec.rb
Labels: unscheduled
